#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 12
#define STATE_COUNT 138
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 49
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 7

enum {
  anon_sym_import = 1,
  anon_sym_LBRACE = 2,
  anon_sym_COMMA = 3,
  anon_sym_RBRACE = 4,
  anon_sym_export = 5,
  anon_sym_struct = 6,
  anon_sym_SEMI = 7,
  anon_sym_LPAREN = 8,
  anon_sym_RPAREN = 9,
  anon_sym_COLON = 10,
  anon_sym_LT = 11,
  anon_sym_GT = 12,
  anon_sym_union = 13,
  anon_sym_func = 14,
  anon_sym_DASH_GT = 15,
  anon_sym_let = 16,
  anon_sym_EQ = 17,
  sym_identifier = 18,
  sym_number = 19,
  sym_comment = 20,
  sym_source_file = 21,
  sym__item = 22,
  sym_import_item = 23,
  sym_export_item = 24,
  sym_struct_item = 25,
  sym_struct_parameter_list = 26,
  sym_struct_parameter = 27,
  sym_generic_parameter_list = 28,
  sym_generic_parameter = 29,
  sym_union_item = 30,
  sym_union_variant_list = 31,
  sym_union_variant = 32,
  sym_function_item = 33,
  sym_func_parameter_list = 34,
  sym_func_parameter = 35,
  sym__type = 36,
  sym_block = 37,
  sym__statement = 38,
  sym_let_statement = 39,
  sym__expression = 40,
  sym__pattern = 41,
  aux_sym_source_file_repeat1 = 42,
  aux_sym_import_item_repeat1 = 43,
  aux_sym_struct_parameter_list_repeat1 = 44,
  aux_sym_generic_parameter_list_repeat1 = 45,
  aux_sym_union_variant_list_repeat1 = 46,
  aux_sym_func_parameter_list_repeat1 = 47,
  aux_sym_block_repeat1 = 48,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_import] = "import",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_export] = "export",
  [anon_sym_struct] = "struct",
  [anon_sym_SEMI] = ";",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_union] = "union",
  [anon_sym_func] = "func",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__item] = "_item",
  [sym_import_item] = "import_item",
  [sym_export_item] = "export_item",
  [sym_struct_item] = "struct_item",
  [sym_struct_parameter_list] = "struct_parameter_list",
  [sym_struct_parameter] = "struct_parameter",
  [sym_generic_parameter_list] = "generic_parameter_list",
  [sym_generic_parameter] = "generic_parameter",
  [sym_union_item] = "union_item",
  [sym_union_variant_list] = "union_variant_list",
  [sym_union_variant] = "union_variant",
  [sym_function_item] = "function_item",
  [sym_func_parameter_list] = "func_parameter_list",
  [sym_func_parameter] = "func_parameter",
  [sym__type] = "_type",
  [sym_block] = "block",
  [sym__statement] = "_statement",
  [sym_let_statement] = "let_statement",
  [sym__expression] = "_expression",
  [sym__pattern] = "_pattern",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_import_item_repeat1] = "import_item_repeat1",
  [aux_sym_struct_parameter_list_repeat1] = "struct_parameter_list_repeat1",
  [aux_sym_generic_parameter_list_repeat1] = "generic_parameter_list_repeat1",
  [aux_sym_union_variant_list_repeat1] = "union_variant_list_repeat1",
  [aux_sym_func_parameter_list_repeat1] = "func_parameter_list_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_export] = anon_sym_export,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_union] = anon_sym_union,
  [anon_sym_func] = anon_sym_func,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__item] = sym__item,
  [sym_import_item] = sym_import_item,
  [sym_export_item] = sym_export_item,
  [sym_struct_item] = sym_struct_item,
  [sym_struct_parameter_list] = sym_struct_parameter_list,
  [sym_struct_parameter] = sym_struct_parameter,
  [sym_generic_parameter_list] = sym_generic_parameter_list,
  [sym_generic_parameter] = sym_generic_parameter,
  [sym_union_item] = sym_union_item,
  [sym_union_variant_list] = sym_union_variant_list,
  [sym_union_variant] = sym_union_variant,
  [sym_function_item] = sym_function_item,
  [sym_func_parameter_list] = sym_func_parameter_list,
  [sym_func_parameter] = sym_func_parameter,
  [sym__type] = sym__type,
  [sym_block] = sym_block,
  [sym__statement] = sym__statement,
  [sym_let_statement] = sym_let_statement,
  [sym__expression] = sym__expression,
  [sym__pattern] = sym__pattern,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_import_item_repeat1] = aux_sym_import_item_repeat1,
  [aux_sym_struct_parameter_list_repeat1] = aux_sym_struct_parameter_list_repeat1,
  [aux_sym_generic_parameter_list_repeat1] = aux_sym_generic_parameter_list_repeat1,
  [aux_sym_union_variant_list_repeat1] = aux_sym_union_variant_list_repeat1,
  [aux_sym_func_parameter_list_repeat1] = aux_sym_func_parameter_list_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_export] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_union] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_func] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_import_item] = {
    .visible = true,
    .named = true,
  },
  [sym_export_item] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_item] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_generic_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_generic_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_union_item] = {
    .visible = true,
    .named = true,
  },
  [sym_union_variant_list] = {
    .visible = true,
    .named = true,
  },
  [sym_union_variant] = {
    .visible = true,
    .named = true,
  },
  [sym_function_item] = {
    .visible = true,
    .named = true,
  },
  [sym_func_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_func_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_let_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__pattern] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_import_item_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_generic_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_union_variant_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_func_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_body = 1,
  field_bounds = 2,
  field_generics = 3,
  field_name = 4,
  field_parameters = 5,
  field_pattern = 6,
  field_return_type = 7,
  field_trailing = 8,
  field_type = 9,
  field_value = 10,
  field_variants = 11,
};

static const char *ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_bounds] = "bounds",
  [field_generics] = "generics",
  [field_name] = "name",
  [field_parameters] = "parameters",
  [field_pattern] = "pattern",
  [field_return_type] = "return_type",
  [field_trailing] = "trailing",
  [field_type] = "type",
  [field_value] = "value",
  [field_variants] = "variants",
};

static const TSFieldMapSlice ts_field_map_slices[18] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 3},
  [6] = {.index = 9, .length = 2},
  [7] = {.index = 11, .length = 3},
  [8] = {.index = 14, .length = 2},
  [9] = {.index = 16, .length = 2},
  [10] = {.index = 18, .length = 2},
  [11] = {.index = 20, .length = 4},
  [12] = {.index = 24, .length = 3},
  [13] = {.index = 27, .length = 5},
  [14] = {.index = 32, .length = 1},
  [15] = {.index = 33, .length = 1},
  [16] = {.index = 34, .length = 2},
  [17] = {.index = 36, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_type, 0},
  [1] =
    {field_name, 0},
  [2] =
    {field_name, 1},
    {field_parameters, 2},
  [4] =
    {field_name, 1},
    {field_variants, 2},
  [6] =
    {field_generics, 2},
    {field_name, 1},
    {field_parameters, 3},
  [9] =
    {field_name, 0},
    {field_parameters, 1},
  [11] =
    {field_generics, 2},
    {field_name, 1},
    {field_variants, 3},
  [14] =
    {field_name, 0},
    {field_type, 2},
  [16] =
    {field_bounds, 2},
    {field_name, 0},
  [18] =
    {field_pattern, 0},
    {field_type, 2},
  [20] =
    {field_body, 5},
    {field_name, 1},
    {field_parameters, 2},
    {field_return_type, 4},
  [24] =
    {field_name, 0},
    {field_pattern, 1},
    {field_type, 3},
  [27] =
    {field_body, 6},
    {field_generics, 2},
    {field_name, 1},
    {field_parameters, 3},
    {field_return_type, 5},
  [32] =
    {field_trailing, 1},
  [33] =
    {field_trailing, 2},
  [34] =
    {field_name, 1},
    {field_value, 3},
  [36] =
    {field_name, 1},
    {field_type, 2},
    {field_type, 3},
    {field_value, 5},
};

static TSSymbol ts_alias_sequences[18][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(32);
      if (lookahead == '(') ADVANCE(40);
      if (lookahead == ')') ADVANCE(41);
      if (lookahead == '+') ADVANCE(31);
      if (lookahead == ',') ADVANCE(35);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == ':') ADVANCE(42);
      if (lookahead == ';') ADVANCE(39);
      if (lookahead == '<') ADVANCE(43);
      if (lookahead == '=') ADVANCE(50);
      if (lookahead == '>') ADVANCE(44);
      if (lookahead == 'e') ADVANCE(30);
      if (lookahead == 'f') ADVANCE(28);
      if (lookahead == 'i') ADVANCE(11);
      if (lookahead == 'l') ADVANCE(9);
      if (lookahead == 's') ADVANCE(23);
      if (lookahead == 'u') ADVANCE(12);
      if (lookahead == '{') ADVANCE(34);
      if (lookahead == '}') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 1:
      if (lookahead == ')') ADVANCE(41);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == ':') ADVANCE(42);
      if (lookahead == '>') ADVANCE(44);
      if (lookahead == '}') ADVANCE(36);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(56);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(55);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == 'l') ADVANCE(51);
      if (lookahead == '}') ADVANCE(36);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(46);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(27);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(16);
      END_STATE();
    case 11:
      if (lookahead == 'm') ADVANCE(19);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(45);
      END_STATE();
    case 15:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 16:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 18:
      if (lookahead == 'p') ADVANCE(15);
      END_STATE();
    case 19:
      if (lookahead == 'p') ADVANCE(17);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(48);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 28:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 29:
      if (lookahead == 'u') ADVANCE(8);
      END_STATE();
    case 30:
      if (lookahead == 'x') ADVANCE(18);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_export);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_union);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_func);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(56);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 5},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 5},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 5},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 5},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 1},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 1},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 1},
  [94] = {.lex_state = 1},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 1},
  [98] = {.lex_state = 1},
  [99] = {.lex_state = 1},
  [100] = {.lex_state = 1},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 1},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 1},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 1},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 1},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 1},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_export] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_union] = ACTIONS(1),
    [anon_sym_func] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(125),
    [sym__item] = STATE(2),
    [sym_import_item] = STATE(2),
    [sym_export_item] = STATE(2),
    [sym_struct_item] = STATE(2),
    [sym_union_item] = STATE(2),
    [sym_function_item] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_import] = ACTIONS(7),
    [anon_sym_export] = ACTIONS(9),
    [anon_sym_struct] = ACTIONS(11),
    [anon_sym_union] = ACTIONS(13),
    [anon_sym_func] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_export,
    ACTIONS(11), 1,
      anon_sym_struct,
    ACTIONS(13), 1,
      anon_sym_union,
    ACTIONS(15), 1,
      anon_sym_func,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(3), 7,
      sym__item,
      sym_import_item,
      sym_export_item,
      sym_struct_item,
      sym_union_item,
      sym_function_item,
      aux_sym_source_file_repeat1,
  [31] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_import,
    ACTIONS(24), 1,
      anon_sym_export,
    ACTIONS(27), 1,
      anon_sym_struct,
    ACTIONS(30), 1,
      anon_sym_union,
    ACTIONS(33), 1,
      anon_sym_func,
    STATE(3), 7,
      sym__item,
      sym_import_item,
      sym_export_item,
      sym_struct_item,
      sym_union_item,
      sym_function_item,
      aux_sym_source_file_repeat1,
  [62] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(36), 1,
      anon_sym_RBRACE,
    ACTIONS(38), 1,
      anon_sym_let,
    ACTIONS(40), 1,
      sym_identifier,
    ACTIONS(42), 1,
      sym_number,
    STATE(77), 1,
      sym__expression,
    STATE(6), 3,
      sym__statement,
      sym_let_statement,
      aux_sym_block_repeat1,
  [86] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(38), 1,
      anon_sym_let,
    ACTIONS(44), 1,
      anon_sym_RBRACE,
    ACTIONS(46), 1,
      sym_identifier,
    ACTIONS(48), 1,
      sym_number,
    STATE(88), 1,
      sym__expression,
    STATE(4), 3,
      sym__statement,
      sym_let_statement,
      aux_sym_block_repeat1,
  [110] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      anon_sym_RBRACE,
    ACTIONS(52), 1,
      anon_sym_let,
    ACTIONS(55), 1,
      sym_identifier,
    ACTIONS(58), 1,
      sym_number,
    STATE(131), 1,
      sym__expression,
    STATE(6), 3,
      sym__statement,
      sym_let_statement,
      aux_sym_block_repeat1,
  [134] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [146] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [158] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [170] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [182] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [194] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [206] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [218] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [230] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [242] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [254] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [266] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [278] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [290] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [302] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [314] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [326] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [338] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [350] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      anon_sym_RPAREN,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(101), 1,
      sym_number,
    STATE(56), 1,
      sym_func_parameter,
    STATE(109), 1,
      sym__pattern,
  [369] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(101), 1,
      sym_number,
    ACTIONS(103), 1,
      anon_sym_RPAREN,
    STATE(101), 1,
      sym_func_parameter,
    STATE(109), 1,
      sym__pattern,
  [388] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(101), 1,
      sym_number,
    ACTIONS(105), 1,
      anon_sym_RPAREN,
    STATE(101), 1,
      sym_func_parameter,
    STATE(109), 1,
      sym__pattern,
  [407] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_RPAREN,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(75), 1,
      sym__type,
    STATE(87), 1,
      sym_struct_parameter,
  [423] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(113), 2,
      anon_sym_let,
      sym_identifier,
  [435] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(101), 1,
      sym_number,
    STATE(101), 1,
      sym_func_parameter,
    STATE(109), 1,
      sym__pattern,
  [451] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_COLON,
    STATE(126), 1,
      sym__pattern,
    ACTIONS(117), 2,
      sym_identifier,
      sym_number,
  [465] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      sym_identifier,
    ACTIONS(119), 1,
      anon_sym_RPAREN,
    STATE(46), 1,
      sym_struct_parameter,
    STATE(75), 1,
      sym__type,
  [481] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    ACTIONS(123), 1,
      anon_sym_LT,
    STATE(85), 1,
      sym_generic_parameter_list,
    STATE(123), 1,
      sym_func_parameter_list,
  [497] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_LT,
    ACTIONS(125), 1,
      anon_sym_LPAREN,
    STATE(102), 1,
      sym_generic_parameter_list,
    STATE(122), 1,
      sym_union_variant_list,
  [513] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(129), 2,
      anon_sym_let,
      sym_identifier,
  [525] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_LPAREN,
    STATE(83), 1,
      sym_struct_parameter_list,
    ACTIONS(131), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [539] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      sym_identifier,
    ACTIONS(135), 1,
      anon_sym_RPAREN,
    STATE(75), 1,
      sym__type,
    STATE(87), 1,
      sym_struct_parameter,
  [555] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_LT,
    ACTIONS(133), 1,
      anon_sym_LPAREN,
    STATE(95), 1,
      sym_generic_parameter_list,
    STATE(116), 1,
      sym_struct_parameter_list,
  [571] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(139), 2,
      anon_sym_let,
      sym_identifier,
  [583] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_COMMA,
    ACTIONS(143), 1,
      anon_sym_GT,
    STATE(63), 1,
      aux_sym_generic_parameter_list_repeat1,
  [596] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      anon_sym_COMMA,
    ACTIONS(147), 1,
      anon_sym_RPAREN,
    STATE(60), 1,
      aux_sym_union_variant_list_repeat1,
  [609] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(136), 1,
      sym__expression,
    ACTIONS(149), 2,
      sym_identifier,
      sym_number,
  [620] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      anon_sym_COMMA,
    ACTIONS(153), 1,
      anon_sym_RBRACE,
    STATE(62), 1,
      aux_sym_import_item_repeat1,
  [633] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 3,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [642] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_COLON,
    ACTIONS(157), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [653] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_COMMA,
    ACTIONS(163), 1,
      anon_sym_RPAREN,
    STATE(66), 1,
      aux_sym_struct_parameter_list_repeat1,
  [666] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(133), 1,
      sym__expression,
    ACTIONS(165), 2,
      sym_identifier,
      sym_number,
  [677] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      anon_sym_COMMA,
    ACTIONS(169), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_import_item_repeat1,
  [690] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_COLON,
    ACTIONS(171), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [701] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_COMMA,
    ACTIONS(177), 1,
      anon_sym_GT,
    STATE(40), 1,
      aux_sym_generic_parameter_list_repeat1,
  [714] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(84), 1,
      sym__pattern,
    ACTIONS(179), 2,
      sym_identifier,
      sym_number,
  [725] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      anon_sym_COMMA,
    ACTIONS(183), 1,
      anon_sym_RBRACE,
    STATE(43), 1,
      aux_sym_import_item_repeat1,
  [738] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      anon_sym_COMMA,
    ACTIONS(187), 1,
      anon_sym_RPAREN,
    STATE(41), 1,
      aux_sym_union_variant_list_repeat1,
  [751] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_GT,
    ACTIONS(191), 1,
      sym_identifier,
    STATE(50), 1,
      sym_generic_parameter,
  [764] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(75), 1,
      sym__type,
    STATE(87), 1,
      sym_struct_parameter,
  [777] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      anon_sym_COMMA,
    ACTIONS(195), 1,
      anon_sym_RPAREN,
    STATE(70), 1,
      aux_sym_func_parameter_list_repeat1,
  [790] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 3,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [799] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_RPAREN,
    ACTIONS(201), 1,
      sym_identifier,
    STATE(53), 1,
      sym_union_variant,
  [812] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_COMMA,
    ACTIONS(206), 1,
      anon_sym_RPAREN,
    STATE(59), 1,
      aux_sym_func_parameter_list_repeat1,
  [825] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_COMMA,
    ACTIONS(211), 1,
      anon_sym_RPAREN,
    STATE(60), 1,
      aux_sym_union_variant_list_repeat1,
  [838] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      sym_identifier,
    ACTIONS(213), 1,
      anon_sym_RPAREN,
    STATE(96), 1,
      sym_union_variant,
  [851] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_COMMA,
    ACTIONS(218), 1,
      anon_sym_RBRACE,
    STATE(62), 1,
      aux_sym_import_item_repeat1,
  [864] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_COMMA,
    ACTIONS(223), 1,
      anon_sym_GT,
    STATE(63), 1,
      aux_sym_generic_parameter_list_repeat1,
  [877] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      sym_identifier,
    ACTIONS(225), 1,
      anon_sym_GT,
    STATE(92), 1,
      sym_generic_parameter,
  [890] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 3,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [899] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      anon_sym_RPAREN,
    ACTIONS(229), 1,
      anon_sym_COMMA,
    STATE(69), 1,
      aux_sym_struct_parameter_list_repeat1,
  [912] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_COMMA,
    ACTIONS(233), 1,
      anon_sym_RBRACE,
    STATE(62), 1,
      aux_sym_import_item_repeat1,
  [925] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      anon_sym_GT,
    ACTIONS(191), 1,
      sym_identifier,
    STATE(92), 1,
      sym_generic_parameter,
  [938] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      anon_sym_COMMA,
    ACTIONS(238), 1,
      anon_sym_RPAREN,
    STATE(69), 1,
      aux_sym_struct_parameter_list_repeat1,
  [951] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_RPAREN,
    ACTIONS(240), 1,
      anon_sym_COMMA,
    STATE(59), 1,
      aux_sym_func_parameter_list_repeat1,
  [964] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_RPAREN,
    ACTIONS(201), 1,
      sym_identifier,
    STATE(96), 1,
      sym_union_variant,
  [977] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 3,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [986] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [994] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 1,
      anon_sym_RBRACE,
    ACTIONS(248), 1,
      sym_identifier,
  [1004] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1012] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      sym_identifier,
    STATE(132), 1,
      sym__type,
  [1022] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      anon_sym_RBRACE,
    ACTIONS(256), 1,
      anon_sym_SEMI,
  [1032] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      anon_sym_RBRACE,
    ACTIONS(258), 1,
      sym_identifier,
  [1042] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      anon_sym_RBRACE,
    ACTIONS(262), 1,
      sym_identifier,
  [1052] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      sym_identifier,
    STATE(104), 1,
      sym__type,
  [1062] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      sym_identifier,
    STATE(105), 1,
      sym__type,
  [1072] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_LBRACE,
    STATE(21), 1,
      sym_block,
  [1082] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1090] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      anon_sym_COLON,
    ACTIONS(274), 1,
      anon_sym_EQ,
  [1100] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    STATE(108), 1,
      sym_func_parameter_list,
  [1110] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1118] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1126] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_SEMI,
    ACTIONS(278), 1,
      anon_sym_RBRACE,
  [1136] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      anon_sym_RBRACE,
    ACTIONS(258), 1,
      sym_identifier,
  [1146] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1154] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      sym_identifier,
    STATE(96), 1,
      sym_union_variant,
  [1164] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [1172] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      sym_identifier,
    STATE(92), 1,
      sym_generic_parameter,
  [1182] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      sym_identifier,
    STATE(86), 1,
      sym__type,
  [1192] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_LPAREN,
    STATE(112), 1,
      sym_struct_parameter_list,
  [1202] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1210] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      sym_identifier,
    ACTIONS(284), 1,
      anon_sym_RBRACE,
  [1220] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      sym_identifier,
    ACTIONS(286), 1,
      anon_sym_RBRACE,
  [1230] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      sym_identifier,
    STATE(90), 1,
      sym__type,
  [1240] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 1,
      sym_identifier,
    STATE(82), 1,
      sym__type,
  [1250] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1258] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_LPAREN,
    STATE(118), 1,
      sym_union_variant_list,
  [1268] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1276] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1284] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_LBRACE,
    STATE(18), 1,
      sym_block,
  [1294] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      sym_identifier,
  [1301] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(294), 1,
      anon_sym_SEMI,
  [1308] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      anon_sym_DASH_GT,
  [1315] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(298), 1,
      anon_sym_COLON,
  [1322] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 1,
      anon_sym_LPAREN,
  [1329] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(302), 1,
      sym_identifier,
  [1336] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 1,
      anon_sym_SEMI,
  [1343] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(306), 1,
      anon_sym_LPAREN,
  [1350] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(308), 1,
      anon_sym_LPAREN,
  [1357] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(310), 1,
      anon_sym_DASH_GT,
  [1364] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(312), 1,
      anon_sym_SEMI,
  [1371] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(314), 1,
      anon_sym_DASH_GT,
  [1378] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(316), 1,
      anon_sym_SEMI,
  [1385] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(318), 1,
      anon_sym_SEMI,
  [1392] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(320), 1,
      sym_identifier,
  [1399] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(322), 1,
      anon_sym_SEMI,
  [1406] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(324), 1,
      anon_sym_SEMI,
  [1413] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(326), 1,
      anon_sym_DASH_GT,
  [1420] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(328), 1,
      anon_sym_DASH_GT,
  [1427] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(330), 1,
      ts_builtin_sym_end,
  [1434] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(332), 1,
      anon_sym_COLON,
  [1441] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(334), 1,
      sym_identifier,
  [1448] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(336), 1,
      anon_sym_LBRACE,
  [1455] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(338), 1,
      anon_sym_LPAREN,
  [1462] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(340), 1,
      sym_identifier,
  [1469] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_SEMI,
  [1476] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(342), 1,
      anon_sym_EQ,
  [1483] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(344), 1,
      anon_sym_SEMI,
  [1490] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(346), 1,
      anon_sym_SEMI,
  [1497] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(348), 1,
      anon_sym_DASH_GT,
  [1504] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(350), 1,
      anon_sym_SEMI,
  [1511] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(352), 1,
      anon_sym_LBRACE,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 31,
  [SMALL_STATE(4)] = 62,
  [SMALL_STATE(5)] = 86,
  [SMALL_STATE(6)] = 110,
  [SMALL_STATE(7)] = 134,
  [SMALL_STATE(8)] = 146,
  [SMALL_STATE(9)] = 158,
  [SMALL_STATE(10)] = 170,
  [SMALL_STATE(11)] = 182,
  [SMALL_STATE(12)] = 194,
  [SMALL_STATE(13)] = 206,
  [SMALL_STATE(14)] = 218,
  [SMALL_STATE(15)] = 230,
  [SMALL_STATE(16)] = 242,
  [SMALL_STATE(17)] = 254,
  [SMALL_STATE(18)] = 266,
  [SMALL_STATE(19)] = 278,
  [SMALL_STATE(20)] = 290,
  [SMALL_STATE(21)] = 302,
  [SMALL_STATE(22)] = 314,
  [SMALL_STATE(23)] = 326,
  [SMALL_STATE(24)] = 338,
  [SMALL_STATE(25)] = 350,
  [SMALL_STATE(26)] = 369,
  [SMALL_STATE(27)] = 388,
  [SMALL_STATE(28)] = 407,
  [SMALL_STATE(29)] = 423,
  [SMALL_STATE(30)] = 435,
  [SMALL_STATE(31)] = 451,
  [SMALL_STATE(32)] = 465,
  [SMALL_STATE(33)] = 481,
  [SMALL_STATE(34)] = 497,
  [SMALL_STATE(35)] = 513,
  [SMALL_STATE(36)] = 525,
  [SMALL_STATE(37)] = 539,
  [SMALL_STATE(38)] = 555,
  [SMALL_STATE(39)] = 571,
  [SMALL_STATE(40)] = 583,
  [SMALL_STATE(41)] = 596,
  [SMALL_STATE(42)] = 609,
  [SMALL_STATE(43)] = 620,
  [SMALL_STATE(44)] = 633,
  [SMALL_STATE(45)] = 642,
  [SMALL_STATE(46)] = 653,
  [SMALL_STATE(47)] = 666,
  [SMALL_STATE(48)] = 677,
  [SMALL_STATE(49)] = 690,
  [SMALL_STATE(50)] = 701,
  [SMALL_STATE(51)] = 714,
  [SMALL_STATE(52)] = 725,
  [SMALL_STATE(53)] = 738,
  [SMALL_STATE(54)] = 751,
  [SMALL_STATE(55)] = 764,
  [SMALL_STATE(56)] = 777,
  [SMALL_STATE(57)] = 790,
  [SMALL_STATE(58)] = 799,
  [SMALL_STATE(59)] = 812,
  [SMALL_STATE(60)] = 825,
  [SMALL_STATE(61)] = 838,
  [SMALL_STATE(62)] = 851,
  [SMALL_STATE(63)] = 864,
  [SMALL_STATE(64)] = 877,
  [SMALL_STATE(65)] = 890,
  [SMALL_STATE(66)] = 899,
  [SMALL_STATE(67)] = 912,
  [SMALL_STATE(68)] = 925,
  [SMALL_STATE(69)] = 938,
  [SMALL_STATE(70)] = 951,
  [SMALL_STATE(71)] = 964,
  [SMALL_STATE(72)] = 977,
  [SMALL_STATE(73)] = 986,
  [SMALL_STATE(74)] = 994,
  [SMALL_STATE(75)] = 1004,
  [SMALL_STATE(76)] = 1012,
  [SMALL_STATE(77)] = 1022,
  [SMALL_STATE(78)] = 1032,
  [SMALL_STATE(79)] = 1042,
  [SMALL_STATE(80)] = 1052,
  [SMALL_STATE(81)] = 1062,
  [SMALL_STATE(82)] = 1072,
  [SMALL_STATE(83)] = 1082,
  [SMALL_STATE(84)] = 1090,
  [SMALL_STATE(85)] = 1100,
  [SMALL_STATE(86)] = 1110,
  [SMALL_STATE(87)] = 1118,
  [SMALL_STATE(88)] = 1126,
  [SMALL_STATE(89)] = 1136,
  [SMALL_STATE(90)] = 1146,
  [SMALL_STATE(91)] = 1154,
  [SMALL_STATE(92)] = 1164,
  [SMALL_STATE(93)] = 1172,
  [SMALL_STATE(94)] = 1182,
  [SMALL_STATE(95)] = 1192,
  [SMALL_STATE(96)] = 1202,
  [SMALL_STATE(97)] = 1210,
  [SMALL_STATE(98)] = 1220,
  [SMALL_STATE(99)] = 1230,
  [SMALL_STATE(100)] = 1240,
  [SMALL_STATE(101)] = 1250,
  [SMALL_STATE(102)] = 1258,
  [SMALL_STATE(103)] = 1268,
  [SMALL_STATE(104)] = 1276,
  [SMALL_STATE(105)] = 1284,
  [SMALL_STATE(106)] = 1294,
  [SMALL_STATE(107)] = 1301,
  [SMALL_STATE(108)] = 1308,
  [SMALL_STATE(109)] = 1315,
  [SMALL_STATE(110)] = 1322,
  [SMALL_STATE(111)] = 1329,
  [SMALL_STATE(112)] = 1336,
  [SMALL_STATE(113)] = 1343,
  [SMALL_STATE(114)] = 1350,
  [SMALL_STATE(115)] = 1357,
  [SMALL_STATE(116)] = 1364,
  [SMALL_STATE(117)] = 1371,
  [SMALL_STATE(118)] = 1378,
  [SMALL_STATE(119)] = 1385,
  [SMALL_STATE(120)] = 1392,
  [SMALL_STATE(121)] = 1399,
  [SMALL_STATE(122)] = 1406,
  [SMALL_STATE(123)] = 1413,
  [SMALL_STATE(124)] = 1420,
  [SMALL_STATE(125)] = 1427,
  [SMALL_STATE(126)] = 1434,
  [SMALL_STATE(127)] = 1441,
  [SMALL_STATE(128)] = 1448,
  [SMALL_STATE(129)] = 1455,
  [SMALL_STATE(130)] = 1462,
  [SMALL_STATE(131)] = 1469,
  [SMALL_STATE(132)] = 1476,
  [SMALL_STATE(133)] = 1483,
  [SMALL_STATE(134)] = 1490,
  [SMALL_STATE(135)] = 1497,
  [SMALL_STATE(136)] = 1504,
  [SMALL_STATE(137)] = 1511,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(128),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(137),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(120),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(130),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(127),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [38] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(51),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(131),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(131),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_item, 4),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_item, 4, .production_id = 3),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_item, 4, .production_id = 4),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, .production_id = 14),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_item, 5),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_item, 5, .production_id = 5),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_item, 4),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_item, 3),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_item, 3),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_item, 7, .production_id = 13),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, .production_id = 15),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_item, 5),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_item, 6, .production_id = 11),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_item, 5, .production_id = 7),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_item, 6),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_item, 6),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 7, .production_id = 17),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_statement, 7, .production_id = 17),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__pattern, 1),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 5, .production_id = 16),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_statement, 5, .production_id = 16),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_variant, 1, .production_id = 2),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 2),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 2),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_parameter_list, 2),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 1),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_parameter, 1, .production_id = 2),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_parameter_list, 5),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [203] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_func_parameter_list_repeat1, 2), SHIFT_REPEAT(30),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_func_parameter_list_repeat1, 2),
  [208] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_union_variant_list_repeat1, 2), SHIFT_REPEAT(91),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_union_variant_list_repeat1, 2),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [215] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_import_item_repeat1, 2), SHIFT_REPEAT(106),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_import_item_repeat1, 2),
  [220] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_generic_parameter_list_repeat1, 2), SHIFT_REPEAT(93),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_generic_parameter_list_repeat1, 2),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_parameter_list, 3),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [235] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_parameter_list_repeat1, 2), SHIFT_REPEAT(55),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_parameter_list_repeat1, 2),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_parameter_list, 4),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_parameter, 3, .production_id = 9),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_parameter, 1, .production_id = 1),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_variant, 2, .production_id = 6),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_parameter, 3, .production_id = 8),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_parameter, 4, .production_id = 12),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_parameter, 3, .production_id = 10),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_variant_list, 5),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_parameter_list, 5),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_parameter_list, 4),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_parameter_list, 3),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_parameter_list, 5),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [314] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_parameter_list, 2),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [318] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_variant_list, 2),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_variant_list, 4),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [328] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_parameter_list, 3),
  [330] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [338] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_parameter_list, 2),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [346] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_variant_list, 3),
  [348] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_parameter_list, 4),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_language_test(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const uint16_t *)ts_parse_table,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .field_count = FIELD_COUNT,
    .field_map_slices = (const TSFieldMapSlice *)ts_field_map_slices,
    .field_map_entries = (const TSFieldMapEntry *)ts_field_map_entries,
    .field_names = ts_field_names,
    .large_state_count = LARGE_STATE_COUNT,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .state_count = STATE_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
