#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 12
#define STATE_COUNT 112
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 7

enum {
  anon_sym_import = 1,
  anon_sym_LBRACE = 2,
  anon_sym_COMMA = 3,
  anon_sym_RBRACE = 4,
  anon_sym_export = 5,
  anon_sym_struct = 6,
  anon_sym_SEMI = 7,
  anon_sym_LPAREN = 8,
  anon_sym_RPAREN = 9,
  anon_sym_COLON = 10,
  anon_sym_union = 11,
  anon_sym_func = 12,
  anon_sym_DASH_GT = 13,
  anon_sym_let = 14,
  anon_sym_EQ = 15,
  sym_identifier = 16,
  sym_number = 17,
  sym_comment = 18,
  sym_source_file = 19,
  sym__item = 20,
  sym_import_item = 21,
  sym_export_item = 22,
  sym_struct_item = 23,
  sym_struct_parameter_list = 24,
  sym_struct_parameter = 25,
  sym_union_item = 26,
  sym_union_variant_list = 27,
  sym_union_variant = 28,
  sym_function_item = 29,
  sym_func_parameter_list = 30,
  sym_func_parameter = 31,
  sym__type = 32,
  sym_block = 33,
  sym__statement = 34,
  sym_let_statement = 35,
  sym__expression = 36,
  sym__pattern = 37,
  aux_sym_source_file_repeat1 = 38,
  aux_sym_import_item_repeat1 = 39,
  aux_sym_struct_parameter_list_repeat1 = 40,
  aux_sym_union_variant_list_repeat1 = 41,
  aux_sym_func_parameter_list_repeat1 = 42,
  aux_sym_block_repeat1 = 43,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_import] = "import",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_export] = "export",
  [anon_sym_struct] = "struct",
  [anon_sym_SEMI] = ";",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_union] = "union",
  [anon_sym_func] = "func",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__item] = "_item",
  [sym_import_item] = "import_item",
  [sym_export_item] = "export_item",
  [sym_struct_item] = "struct_item",
  [sym_struct_parameter_list] = "struct_parameter_list",
  [sym_struct_parameter] = "struct_parameter",
  [sym_union_item] = "union_item",
  [sym_union_variant_list] = "union_variant_list",
  [sym_union_variant] = "union_variant",
  [sym_function_item] = "function_item",
  [sym_func_parameter_list] = "func_parameter_list",
  [sym_func_parameter] = "func_parameter",
  [sym__type] = "_type",
  [sym_block] = "block",
  [sym__statement] = "_statement",
  [sym_let_statement] = "let_statement",
  [sym__expression] = "_expression",
  [sym__pattern] = "_pattern",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_import_item_repeat1] = "import_item_repeat1",
  [aux_sym_struct_parameter_list_repeat1] = "struct_parameter_list_repeat1",
  [aux_sym_union_variant_list_repeat1] = "union_variant_list_repeat1",
  [aux_sym_func_parameter_list_repeat1] = "func_parameter_list_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_export] = anon_sym_export,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_union] = anon_sym_union,
  [anon_sym_func] = anon_sym_func,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__item] = sym__item,
  [sym_import_item] = sym_import_item,
  [sym_export_item] = sym_export_item,
  [sym_struct_item] = sym_struct_item,
  [sym_struct_parameter_list] = sym_struct_parameter_list,
  [sym_struct_parameter] = sym_struct_parameter,
  [sym_union_item] = sym_union_item,
  [sym_union_variant_list] = sym_union_variant_list,
  [sym_union_variant] = sym_union_variant,
  [sym_function_item] = sym_function_item,
  [sym_func_parameter_list] = sym_func_parameter_list,
  [sym_func_parameter] = sym_func_parameter,
  [sym__type] = sym__type,
  [sym_block] = sym_block,
  [sym__statement] = sym__statement,
  [sym_let_statement] = sym_let_statement,
  [sym__expression] = sym__expression,
  [sym__pattern] = sym__pattern,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_import_item_repeat1] = aux_sym_import_item_repeat1,
  [aux_sym_struct_parameter_list_repeat1] = aux_sym_struct_parameter_list_repeat1,
  [aux_sym_union_variant_list_repeat1] = aux_sym_union_variant_list_repeat1,
  [aux_sym_func_parameter_list_repeat1] = aux_sym_func_parameter_list_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_export] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_union] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_func] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_import_item] = {
    .visible = true,
    .named = true,
  },
  [sym_export_item] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_item] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_union_item] = {
    .visible = true,
    .named = true,
  },
  [sym_union_variant_list] = {
    .visible = true,
    .named = true,
  },
  [sym_union_variant] = {
    .visible = true,
    .named = true,
  },
  [sym_function_item] = {
    .visible = true,
    .named = true,
  },
  [sym_func_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_func_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_let_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__pattern] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_import_item_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_union_variant_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_func_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_body = 1,
  field_name = 2,
  field_parameters = 3,
  field_pattern = 4,
  field_return_type = 5,
  field_trailing = 6,
  field_type = 7,
  field_value = 8,
  field_variants = 9,
};

static const char *ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_name] = "name",
  [field_parameters] = "parameters",
  [field_pattern] = "pattern",
  [field_return_type] = "return_type",
  [field_trailing] = "trailing",
  [field_type] = "type",
  [field_value] = "value",
  [field_variants] = "variants",
};

static const TSFieldMapSlice ts_field_map_slices[13] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 2},
  [6] = {.index = 9, .length = 2},
  [7] = {.index = 11, .length = 4},
  [8] = {.index = 15, .length = 3},
  [9] = {.index = 18, .length = 1},
  [10] = {.index = 19, .length = 1},
  [11] = {.index = 20, .length = 2},
  [12] = {.index = 22, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_type, 0},
  [1] =
    {field_name, 1},
    {field_parameters, 2},
  [3] =
    {field_name, 1},
    {field_variants, 2},
  [5] =
    {field_name, 0},
    {field_parameters, 1},
  [7] =
    {field_name, 0},
    {field_type, 2},
  [9] =
    {field_pattern, 0},
    {field_type, 2},
  [11] =
    {field_body, 5},
    {field_name, 1},
    {field_parameters, 2},
    {field_return_type, 4},
  [15] =
    {field_name, 0},
    {field_pattern, 1},
    {field_type, 3},
  [18] =
    {field_trailing, 1},
  [19] =
    {field_trailing, 2},
  [20] =
    {field_name, 1},
    {field_value, 3},
  [22] =
    {field_name, 1},
    {field_type, 2},
    {field_type, 3},
    {field_value, 5},
};

static TSSymbol ts_alias_sequences[13][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(32);
      if (lookahead == '(') ADVANCE(40);
      if (lookahead == ')') ADVANCE(41);
      if (lookahead == '+') ADVANCE(31);
      if (lookahead == ',') ADVANCE(35);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == ':') ADVANCE(42);
      if (lookahead == ';') ADVANCE(39);
      if (lookahead == '=') ADVANCE(48);
      if (lookahead == 'e') ADVANCE(30);
      if (lookahead == 'f') ADVANCE(28);
      if (lookahead == 'i') ADVANCE(11);
      if (lookahead == 'l') ADVANCE(9);
      if (lookahead == 's') ADVANCE(23);
      if (lookahead == 'u') ADVANCE(12);
      if (lookahead == '{') ADVANCE(34);
      if (lookahead == '}') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 1:
      if (lookahead == ')') ADVANCE(41);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == ':') ADVANCE(42);
      if (lookahead == '}') ADVANCE(36);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(54);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(53);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == 'l') ADVANCE(49);
      if (lookahead == '}') ADVANCE(36);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(44);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(27);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(16);
      END_STATE();
    case 11:
      if (lookahead == 'm') ADVANCE(19);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(43);
      END_STATE();
    case 15:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 16:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 18:
      if (lookahead == 'p') ADVANCE(15);
      END_STATE();
    case 19:
      if (lookahead == 'p') ADVANCE(17);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(46);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 28:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 29:
      if (lookahead == 'u') ADVANCE(8);
      END_STATE();
    case 30:
      if (lookahead == 'x') ADVANCE(18);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_export);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_union);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_func);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(54);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 5},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 5},
  [28] = {.lex_state = 5},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 5},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 1},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 1},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 1},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 1},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_export] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_union] = ACTIONS(1),
    [anon_sym_func] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(99),
    [sym__item] = STATE(2),
    [sym_import_item] = STATE(2),
    [sym_export_item] = STATE(2),
    [sym_struct_item] = STATE(2),
    [sym_union_item] = STATE(2),
    [sym_function_item] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_import] = ACTIONS(7),
    [anon_sym_export] = ACTIONS(9),
    [anon_sym_struct] = ACTIONS(11),
    [anon_sym_union] = ACTIONS(13),
    [anon_sym_func] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_export,
    ACTIONS(11), 1,
      anon_sym_struct,
    ACTIONS(13), 1,
      anon_sym_union,
    ACTIONS(15), 1,
      anon_sym_func,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(3), 7,
      sym__item,
      sym_import_item,
      sym_export_item,
      sym_struct_item,
      sym_union_item,
      sym_function_item,
      aux_sym_source_file_repeat1,
  [31] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_import,
    ACTIONS(24), 1,
      anon_sym_export,
    ACTIONS(27), 1,
      anon_sym_struct,
    ACTIONS(30), 1,
      anon_sym_union,
    ACTIONS(33), 1,
      anon_sym_func,
    STATE(3), 7,
      sym__item,
      sym_import_item,
      sym_export_item,
      sym_struct_item,
      sym_union_item,
      sym_function_item,
      aux_sym_source_file_repeat1,
  [62] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(36), 1,
      anon_sym_RBRACE,
    ACTIONS(38), 1,
      anon_sym_let,
    ACTIONS(40), 1,
      sym_identifier,
    ACTIONS(42), 1,
      sym_number,
    STATE(80), 1,
      sym__expression,
    STATE(6), 3,
      sym__statement,
      sym_let_statement,
      aux_sym_block_repeat1,
  [86] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(44), 1,
      anon_sym_RBRACE,
    ACTIONS(46), 1,
      anon_sym_let,
    ACTIONS(49), 1,
      sym_identifier,
    ACTIONS(52), 1,
      sym_number,
    STATE(105), 1,
      sym__expression,
    STATE(5), 3,
      sym__statement,
      sym_let_statement,
      aux_sym_block_repeat1,
  [110] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(38), 1,
      anon_sym_let,
    ACTIONS(55), 1,
      anon_sym_RBRACE,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(59), 1,
      sym_number,
    STATE(66), 1,
      sym__expression,
    STATE(5), 3,
      sym__statement,
      sym_let_statement,
      aux_sym_block_repeat1,
  [134] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [146] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [158] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [170] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [182] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [194] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [206] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [218] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [230] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [242] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [254] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [266] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [278] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [290] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [302] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [314] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_RPAREN,
    ACTIONS(93), 1,
      sym_identifier,
    ACTIONS(95), 1,
      sym_number,
    STATE(45), 1,
      sym_func_parameter,
    STATE(94), 1,
      sym__pattern,
  [333] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      sym_identifier,
    ACTIONS(95), 1,
      sym_number,
    ACTIONS(97), 1,
      anon_sym_RPAREN,
    STATE(79), 1,
      sym_func_parameter,
    STATE(94), 1,
      sym__pattern,
  [352] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      sym_identifier,
    ACTIONS(95), 1,
      sym_number,
    ACTIONS(99), 1,
      anon_sym_RPAREN,
    STATE(79), 1,
      sym_func_parameter,
    STATE(94), 1,
      sym__pattern,
  [371] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_RPAREN,
    ACTIONS(103), 1,
      sym_identifier,
    STATE(62), 1,
      sym__type,
    STATE(70), 1,
      sym_struct_parameter,
  [387] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      sym_identifier,
    ACTIONS(105), 1,
      anon_sym_RPAREN,
    STATE(62), 1,
      sym__type,
    STATE(70), 1,
      sym_struct_parameter,
  [403] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(109), 2,
      anon_sym_let,
      sym_identifier,
  [415] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(113), 2,
      anon_sym_let,
      sym_identifier,
  [427] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      sym_identifier,
    ACTIONS(115), 1,
      anon_sym_RPAREN,
    STATE(39), 1,
      sym_struct_parameter,
    STATE(62), 1,
      sym__type,
  [443] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(119), 2,
      anon_sym_let,
      sym_identifier,
  [455] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      anon_sym_COLON,
    STATE(98), 1,
      sym__pattern,
    ACTIONS(123), 2,
      sym_identifier,
      sym_number,
  [469] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      sym_identifier,
    ACTIONS(95), 1,
      sym_number,
    STATE(79), 1,
      sym_func_parameter,
    STATE(94), 1,
      sym__pattern,
  [485] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_COMMA,
    ACTIONS(127), 1,
      anon_sym_RBRACE,
    STATE(50), 1,
      aux_sym_import_item_repeat1,
  [498] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_COMMA,
    ACTIONS(132), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      aux_sym_struct_parameter_list_repeat1,
  [511] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(110), 1,
      sym__expression,
    ACTIONS(134), 2,
      sym_identifier,
      sym_number,
  [522] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    ACTIONS(138), 1,
      anon_sym_RBRACE,
    STATE(50), 1,
      aux_sym_import_item_repeat1,
  [535] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 3,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [544] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      anon_sym_COLON,
    ACTIONS(142), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [555] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      anon_sym_COMMA,
    ACTIONS(148), 1,
      anon_sym_RPAREN,
    STATE(54), 1,
      aux_sym_struct_parameter_list_repeat1,
  [568] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(107), 1,
      sym__expression,
    ACTIONS(150), 2,
      sym_identifier,
      sym_number,
  [579] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(73), 1,
      sym__pattern,
    ACTIONS(152), 2,
      sym_identifier,
      sym_number,
  [590] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      sym_identifier,
    STATE(62), 1,
      sym__type,
    STATE(70), 1,
      sym_struct_parameter,
  [603] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      anon_sym_COMMA,
    ACTIONS(156), 1,
      anon_sym_RPAREN,
    STATE(58), 1,
      aux_sym_union_variant_list_repeat1,
  [616] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 3,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [625] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      anon_sym_COMMA,
    ACTIONS(162), 1,
      anon_sym_RPAREN,
    STATE(57), 1,
      aux_sym_func_parameter_list_repeat1,
  [638] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_COMMA,
    ACTIONS(166), 1,
      anon_sym_RBRACE,
    STATE(33), 1,
      aux_sym_import_item_repeat1,
  [651] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_COMMA,
    ACTIONS(170), 1,
      anon_sym_RBRACE,
    STATE(36), 1,
      aux_sym_import_item_repeat1,
  [664] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 1,
      anon_sym_COMMA,
    ACTIONS(175), 1,
      anon_sym_RPAREN,
    STATE(48), 1,
      aux_sym_func_parameter_list_repeat1,
  [677] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      anon_sym_COMMA,
    ACTIONS(180), 1,
      anon_sym_RPAREN,
    STATE(49), 1,
      aux_sym_union_variant_list_repeat1,
  [690] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_COMMA,
    ACTIONS(185), 1,
      anon_sym_RBRACE,
    STATE(50), 1,
      aux_sym_import_item_repeat1,
  [703] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_RPAREN,
    ACTIONS(189), 1,
      sym_identifier,
    STATE(60), 1,
      sym_union_variant,
  [716] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      sym_identifier,
    ACTIONS(191), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      sym_union_variant,
  [729] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 3,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [738] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_RPAREN,
    ACTIONS(195), 1,
      anon_sym_COMMA,
    STATE(34), 1,
      aux_sym_struct_parameter_list_repeat1,
  [751] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 3,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [760] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      sym_identifier,
    ACTIONS(199), 1,
      anon_sym_RPAREN,
    STATE(60), 1,
      sym_union_variant,
  [773] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      anon_sym_RPAREN,
    ACTIONS(201), 1,
      anon_sym_COMMA,
    STATE(48), 1,
      aux_sym_func_parameter_list_repeat1,
  [786] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_RPAREN,
    ACTIONS(203), 1,
      anon_sym_COMMA,
    STATE(49), 1,
      aux_sym_union_variant_list_repeat1,
  [799] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_RBRACE,
    ACTIONS(207), 1,
      sym_identifier,
  [809] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [817] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_RBRACE,
    ACTIONS(209), 1,
      sym_identifier,
  [827] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [835] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      sym_identifier,
    STATE(82), 1,
      sym__type,
  [845] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_LBRACE,
    STATE(14), 1,
      sym_block,
  [855] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_LPAREN,
    STATE(69), 1,
      sym_struct_parameter_list,
  [865] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      anon_sym_RBRACE,
    ACTIONS(221), 1,
      anon_sym_SEMI,
  [875] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      anon_sym_RBRACE,
    ACTIONS(225), 1,
      sym_identifier,
  [885] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [893] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [901] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [909] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      sym_identifier,
    STATE(68), 1,
      sym__type,
  [919] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_RBRACE,
    ACTIONS(209), 1,
      sym_identifier,
  [929] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      anon_sym_COLON,
    ACTIONS(235), 1,
      anon_sym_EQ,
  [939] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_LPAREN,
    STATE(103), 1,
      sym_func_parameter_list,
  [949] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      sym_identifier,
    ACTIONS(239), 1,
      anon_sym_RBRACE,
  [959] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      sym_identifier,
    ACTIONS(241), 1,
      anon_sym_RBRACE,
  [969] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      sym_identifier,
    STATE(87), 1,
      sym__type,
  [979] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_LPAREN,
    STATE(95), 1,
      sym_struct_parameter_list,
  [989] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [997] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_SEMI,
    ACTIONS(245), 1,
      anon_sym_RBRACE,
  [1007] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1015] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1023] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      sym_identifier,
    STATE(64), 1,
      sym__type,
  [1033] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      anon_sym_LPAREN,
    STATE(100), 1,
      sym_union_variant_list,
  [1043] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      sym_identifier,
    STATE(106), 1,
      sym__type,
  [1053] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      sym_identifier,
    STATE(60), 1,
      sym_union_variant,
  [1063] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1071] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      sym_identifier,
  [1078] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      sym_identifier,
  [1085] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      anon_sym_DASH_GT,
  [1092] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_LBRACE,
  [1099] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      anon_sym_DASH_GT,
  [1106] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_SEMI,
  [1113] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_COLON,
  [1120] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_SEMI,
  [1127] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      anon_sym_DASH_GT,
  [1134] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      anon_sym_SEMI,
  [1141] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_COLON,
  [1148] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      ts_builtin_sym_end,
  [1155] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      anon_sym_SEMI,
  [1162] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      sym_identifier,
  [1169] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_SEMI,
  [1176] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      anon_sym_DASH_GT,
  [1183] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      sym_identifier,
  [1190] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_SEMI,
  [1197] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_EQ,
  [1204] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 1,
      anon_sym_SEMI,
  [1211] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_SEMI,
  [1218] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 1,
      anon_sym_DASH_GT,
  [1225] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      anon_sym_SEMI,
  [1232] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      anon_sym_LBRACE,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 31,
  [SMALL_STATE(4)] = 62,
  [SMALL_STATE(5)] = 86,
  [SMALL_STATE(6)] = 110,
  [SMALL_STATE(7)] = 134,
  [SMALL_STATE(8)] = 146,
  [SMALL_STATE(9)] = 158,
  [SMALL_STATE(10)] = 170,
  [SMALL_STATE(11)] = 182,
  [SMALL_STATE(12)] = 194,
  [SMALL_STATE(13)] = 206,
  [SMALL_STATE(14)] = 218,
  [SMALL_STATE(15)] = 230,
  [SMALL_STATE(16)] = 242,
  [SMALL_STATE(17)] = 254,
  [SMALL_STATE(18)] = 266,
  [SMALL_STATE(19)] = 278,
  [SMALL_STATE(20)] = 290,
  [SMALL_STATE(21)] = 302,
  [SMALL_STATE(22)] = 314,
  [SMALL_STATE(23)] = 333,
  [SMALL_STATE(24)] = 352,
  [SMALL_STATE(25)] = 371,
  [SMALL_STATE(26)] = 387,
  [SMALL_STATE(27)] = 403,
  [SMALL_STATE(28)] = 415,
  [SMALL_STATE(29)] = 427,
  [SMALL_STATE(30)] = 443,
  [SMALL_STATE(31)] = 455,
  [SMALL_STATE(32)] = 469,
  [SMALL_STATE(33)] = 485,
  [SMALL_STATE(34)] = 498,
  [SMALL_STATE(35)] = 511,
  [SMALL_STATE(36)] = 522,
  [SMALL_STATE(37)] = 535,
  [SMALL_STATE(38)] = 544,
  [SMALL_STATE(39)] = 555,
  [SMALL_STATE(40)] = 568,
  [SMALL_STATE(41)] = 579,
  [SMALL_STATE(42)] = 590,
  [SMALL_STATE(43)] = 603,
  [SMALL_STATE(44)] = 616,
  [SMALL_STATE(45)] = 625,
  [SMALL_STATE(46)] = 638,
  [SMALL_STATE(47)] = 651,
  [SMALL_STATE(48)] = 664,
  [SMALL_STATE(49)] = 677,
  [SMALL_STATE(50)] = 690,
  [SMALL_STATE(51)] = 703,
  [SMALL_STATE(52)] = 716,
  [SMALL_STATE(53)] = 729,
  [SMALL_STATE(54)] = 738,
  [SMALL_STATE(55)] = 751,
  [SMALL_STATE(56)] = 760,
  [SMALL_STATE(57)] = 773,
  [SMALL_STATE(58)] = 786,
  [SMALL_STATE(59)] = 799,
  [SMALL_STATE(60)] = 809,
  [SMALL_STATE(61)] = 817,
  [SMALL_STATE(62)] = 827,
  [SMALL_STATE(63)] = 835,
  [SMALL_STATE(64)] = 845,
  [SMALL_STATE(65)] = 855,
  [SMALL_STATE(66)] = 865,
  [SMALL_STATE(67)] = 875,
  [SMALL_STATE(68)] = 885,
  [SMALL_STATE(69)] = 893,
  [SMALL_STATE(70)] = 901,
  [SMALL_STATE(71)] = 909,
  [SMALL_STATE(72)] = 919,
  [SMALL_STATE(73)] = 929,
  [SMALL_STATE(74)] = 939,
  [SMALL_STATE(75)] = 949,
  [SMALL_STATE(76)] = 959,
  [SMALL_STATE(77)] = 969,
  [SMALL_STATE(78)] = 979,
  [SMALL_STATE(79)] = 989,
  [SMALL_STATE(80)] = 997,
  [SMALL_STATE(81)] = 1007,
  [SMALL_STATE(82)] = 1015,
  [SMALL_STATE(83)] = 1023,
  [SMALL_STATE(84)] = 1033,
  [SMALL_STATE(85)] = 1043,
  [SMALL_STATE(86)] = 1053,
  [SMALL_STATE(87)] = 1063,
  [SMALL_STATE(88)] = 1071,
  [SMALL_STATE(89)] = 1078,
  [SMALL_STATE(90)] = 1085,
  [SMALL_STATE(91)] = 1092,
  [SMALL_STATE(92)] = 1099,
  [SMALL_STATE(93)] = 1106,
  [SMALL_STATE(94)] = 1113,
  [SMALL_STATE(95)] = 1120,
  [SMALL_STATE(96)] = 1127,
  [SMALL_STATE(97)] = 1134,
  [SMALL_STATE(98)] = 1141,
  [SMALL_STATE(99)] = 1148,
  [SMALL_STATE(100)] = 1155,
  [SMALL_STATE(101)] = 1162,
  [SMALL_STATE(102)] = 1169,
  [SMALL_STATE(103)] = 1176,
  [SMALL_STATE(104)] = 1183,
  [SMALL_STATE(105)] = 1190,
  [SMALL_STATE(106)] = 1197,
  [SMALL_STATE(107)] = 1204,
  [SMALL_STATE(108)] = 1211,
  [SMALL_STATE(109)] = 1218,
  [SMALL_STATE(110)] = 1225,
  [SMALL_STATE(111)] = 1232,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(91),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(111),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(88),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(104),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(101),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [38] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(41),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(105),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(105),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_item, 4),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_item, 5),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_item, 6),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, .production_id = 9),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, .production_id = 10),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_item, 5),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_item, 6, .production_id = 7),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_item, 3),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_item, 4, .production_id = 3),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_item, 3),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_item, 4),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_item, 4, .production_id = 2),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_item, 6),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 5, .production_id = 11),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_statement, 5, .production_id = 11),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 7, .production_id = 12),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_statement, 7, .production_id = 12),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 2),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 2),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__pattern, 1),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_parameter_list_repeat1, 2), SHIFT_REPEAT(42),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_parameter_list_repeat1, 2),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_parameter_list, 2),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 1),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_parameter_list, 5),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [172] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_func_parameter_list_repeat1, 2), SHIFT_REPEAT(32),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_func_parameter_list_repeat1, 2),
  [177] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_union_variant_list_repeat1, 2), SHIFT_REPEAT(86),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_union_variant_list_repeat1, 2),
  [182] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_import_item_repeat1, 2), SHIFT_REPEAT(89),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_import_item_repeat1, 2),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_parameter_list, 3),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_parameter_list, 4),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_parameter, 1, .production_id = 1),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_parameter, 3, .production_id = 5),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_variant, 2, .production_id = 4),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_parameter, 3, .production_id = 6),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_parameter, 4, .production_id = 8),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_parameter_list, 5),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_parameter_list, 3),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_variant_list, 2),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_parameter_list, 4),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_variant_list, 4),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [277] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_variant_list, 5),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_variant_list, 3),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_parameter_list, 2),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_language_test(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const uint16_t *)ts_parse_table,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .field_count = FIELD_COUNT,
    .field_map_slices = (const TSFieldMapSlice *)ts_field_map_slices,
    .field_map_entries = (const TSFieldMapEntry *)ts_field_map_entries,
    .field_names = ts_field_names,
    .large_state_count = LARGE_STATE_COUNT,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .state_count = STATE_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
