[package]
name = "syntax"
version = "0.1.0"
authors = ["jamesBeeProg <jamesbeeprog@gmail.com>"]
edition = "2018"

[dependencies]
tree-sitter = "0.17.1"
thiserror = "1.0"

[build-dependencies]
cc = "1.0"
