#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 12
#define STATE_COUNT 161
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 51
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 8

enum {
  anon_sym_SEMI = 1,
  anon_sym_module = 2,
  anon_sym_DASH_GT = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  anon_sym_import = 6,
  anon_sym_COMMA = 7,
  anon_sym_export = 8,
  anon_sym_struct = 9,
  anon_sym_LPAREN = 10,
  anon_sym_RPAREN = 11,
  anon_sym_COLON = 12,
  anon_sym_LT = 13,
  anon_sym_GT = 14,
  anon_sym_union = 15,
  anon_sym_func = 16,
  anon_sym_let = 17,
  anon_sym_EQ = 18,
  sym_identifier = 19,
  sym_number = 20,
  sym_comment = 21,
  sym_source_file = 22,
  sym__item = 23,
  sym_module_item = 24,
  sym_import_item = 25,
  sym_export_item = 26,
  sym_struct_item = 27,
  sym_struct_parameter_list = 28,
  sym_struct_parameter = 29,
  sym_generic_parameter_list = 30,
  sym_generic_parameter = 31,
  sym_union_item = 32,
  sym_union_variant_list = 33,
  sym_union_variant = 34,
  sym_function_item = 35,
  sym_func_parameter_list = 36,
  sym_func_parameter = 37,
  sym__type = 38,
  sym_block = 39,
  sym__statement = 40,
  sym_let_statement = 41,
  sym__expression = 42,
  sym__pattern = 43,
  aux_sym_source_file_repeat1 = 44,
  aux_sym_import_item_repeat1 = 45,
  aux_sym_struct_parameter_list_repeat1 = 46,
  aux_sym_generic_parameter_list_repeat1 = 47,
  aux_sym_union_variant_list_repeat1 = 48,
  aux_sym_func_parameter_list_repeat1 = 49,
  aux_sym_block_repeat1 = 50,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_module] = "module",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_import] = "import",
  [anon_sym_COMMA] = ",",
  [anon_sym_export] = "export",
  [anon_sym_struct] = "struct",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_union] = "union",
  [anon_sym_func] = "func",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__item] = "_item",
  [sym_module_item] = "module_item",
  [sym_import_item] = "import_item",
  [sym_export_item] = "export_item",
  [sym_struct_item] = "struct_item",
  [sym_struct_parameter_list] = "struct_parameter_list",
  [sym_struct_parameter] = "struct_parameter",
  [sym_generic_parameter_list] = "generic_parameter_list",
  [sym_generic_parameter] = "generic_parameter",
  [sym_union_item] = "union_item",
  [sym_union_variant_list] = "union_variant_list",
  [sym_union_variant] = "union_variant",
  [sym_function_item] = "function_item",
  [sym_func_parameter_list] = "func_parameter_list",
  [sym_func_parameter] = "func_parameter",
  [sym__type] = "_type",
  [sym_block] = "block",
  [sym__statement] = "_statement",
  [sym_let_statement] = "let_statement",
  [sym__expression] = "_expression",
  [sym__pattern] = "_pattern",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_import_item_repeat1] = "import_item_repeat1",
  [aux_sym_struct_parameter_list_repeat1] = "struct_parameter_list_repeat1",
  [aux_sym_generic_parameter_list_repeat1] = "generic_parameter_list_repeat1",
  [aux_sym_union_variant_list_repeat1] = "union_variant_list_repeat1",
  [aux_sym_func_parameter_list_repeat1] = "func_parameter_list_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_module] = anon_sym_module,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_export] = anon_sym_export,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_union] = anon_sym_union,
  [anon_sym_func] = anon_sym_func,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__item] = sym__item,
  [sym_module_item] = sym_module_item,
  [sym_import_item] = sym_import_item,
  [sym_export_item] = sym_export_item,
  [sym_struct_item] = sym_struct_item,
  [sym_struct_parameter_list] = sym_struct_parameter_list,
  [sym_struct_parameter] = sym_struct_parameter,
  [sym_generic_parameter_list] = sym_generic_parameter_list,
  [sym_generic_parameter] = sym_generic_parameter,
  [sym_union_item] = sym_union_item,
  [sym_union_variant_list] = sym_union_variant_list,
  [sym_union_variant] = sym_union_variant,
  [sym_function_item] = sym_function_item,
  [sym_func_parameter_list] = sym_func_parameter_list,
  [sym_func_parameter] = sym_func_parameter,
  [sym__type] = sym__type,
  [sym_block] = sym_block,
  [sym__statement] = sym__statement,
  [sym_let_statement] = sym_let_statement,
  [sym__expression] = sym__expression,
  [sym__pattern] = sym__pattern,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_import_item_repeat1] = aux_sym_import_item_repeat1,
  [aux_sym_struct_parameter_list_repeat1] = aux_sym_struct_parameter_list_repeat1,
  [aux_sym_generic_parameter_list_repeat1] = aux_sym_generic_parameter_list_repeat1,
  [aux_sym_union_variant_list_repeat1] = aux_sym_union_variant_list_repeat1,
  [aux_sym_func_parameter_list_repeat1] = aux_sym_func_parameter_list_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_module] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_export] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_union] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_func] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_module_item] = {
    .visible = true,
    .named = true,
  },
  [sym_import_item] = {
    .visible = true,
    .named = true,
  },
  [sym_export_item] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_item] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_generic_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_generic_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_union_item] = {
    .visible = true,
    .named = true,
  },
  [sym_union_variant_list] = {
    .visible = true,
    .named = true,
  },
  [sym_union_variant] = {
    .visible = true,
    .named = true,
  },
  [sym_function_item] = {
    .visible = true,
    .named = true,
  },
  [sym_func_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_func_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_let_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__pattern] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_import_item_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_generic_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_union_variant_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_func_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_body = 1,
  field_bounds = 2,
  field_generics = 3,
  field_name = 4,
  field_parameters = 5,
  field_pattern = 6,
  field_return_type = 7,
  field_trailing = 8,
  field_type = 9,
  field_value = 10,
  field_variants = 11,
};

static const char *ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_bounds] = "bounds",
  [field_generics] = "generics",
  [field_name] = "name",
  [field_parameters] = "parameters",
  [field_pattern] = "pattern",
  [field_return_type] = "return_type",
  [field_trailing] = "trailing",
  [field_type] = "type",
  [field_value] = "value",
  [field_variants] = "variants",
};

static const TSFieldMapSlice ts_field_map_slices[24] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 1},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 1},
  [6] = {.index = 7, .length = 3},
  [7] = {.index = 10, .length = 3},
  [8] = {.index = 13, .length = 3},
  [9] = {.index = 16, .length = 2},
  [10] = {.index = 18, .length = 2},
  [11] = {.index = 20, .length = 4},
  [12] = {.index = 24, .length = 2},
  [13] = {.index = 26, .length = 2},
  [14] = {.index = 28, .length = 2},
  [15] = {.index = 30, .length = 2},
  [16] = {.index = 32, .length = 4},
  [17] = {.index = 36, .length = 1},
  [18] = {.index = 37, .length = 3},
  [19] = {.index = 40, .length = 3},
  [20] = {.index = 43, .length = 5},
  [21] = {.index = 48, .length = 1},
  [22] = {.index = 49, .length = 2},
  [23] = {.index = 51, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
    {field_parameters, 2},
  [2] =
    {field_name, 1},
    {field_variants, 2},
  [4] =
    {field_name, 1},
  [5] =
    {field_name, 0},
  [6] =
    {field_type, 0},
  [7] =
    {field_generics, 2},
    {field_name, 1},
    {field_parameters, 3},
  [10] =
    {field_generics, 2},
    {field_name, 1},
    {field_variants, 3},
  [13] =
    {field_body, 3},
    {field_name, 1},
    {field_parameters, 2},
  [16] =
    {field_generics, 2},
    {field_name, 1},
  [18] =
    {field_name, 0},
    {field_parameters, 1},
  [20] =
    {field_body, 4},
    {field_generics, 2},
    {field_name, 1},
    {field_parameters, 3},
  [24] =
    {field_name, 1},
    {field_return_type, 3},
  [26] =
    {field_bounds, 2},
    {field_name, 0},
  [28] =
    {field_name, 0},
    {field_type, 2},
  [30] =
    {field_pattern, 0},
    {field_type, 2},
  [32] =
    {field_body, 5},
    {field_name, 1},
    {field_parameters, 2},
    {field_return_type, 4},
  [36] =
    {field_trailing, 1},
  [37] =
    {field_generics, 2},
    {field_name, 1},
    {field_return_type, 4},
  [40] =
    {field_name, 0},
    {field_pattern, 1},
    {field_type, 3},
  [43] =
    {field_body, 6},
    {field_generics, 2},
    {field_name, 1},
    {field_parameters, 3},
    {field_return_type, 5},
  [48] =
    {field_trailing, 2},
  [49] =
    {field_name, 1},
    {field_value, 3},
  [51] =
    {field_name, 1},
    {field_type, 2},
    {field_type, 3},
    {field_value, 5},
};

static TSSymbol ts_alias_sequences[24][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(37);
      if (lookahead == '(') ADVANCE(47);
      if (lookahead == ')') ADVANCE(48);
      if (lookahead == '+') ADVANCE(36);
      if (lookahead == ',') ADVANCE(44);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == ':') ADVANCE(49);
      if (lookahead == ';') ADVANCE(38);
      if (lookahead == '<') ADVANCE(50);
      if (lookahead == '=') ADVANCE(56);
      if (lookahead == '>') ADVANCE(51);
      if (lookahead == 'e') ADVANCE(35);
      if (lookahead == 'f') ADVANCE(33);
      if (lookahead == 'i') ADVANCE(14);
      if (lookahead == 'l') ADVANCE(11);
      if (lookahead == 'm') ADVANCE(18);
      if (lookahead == 's') ADVANCE(27);
      if (lookahead == 'u') ADVANCE(15);
      if (lookahead == '{') ADVANCE(41);
      if (lookahead == '}') ADVANCE(42);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      END_STATE();
    case 1:
      if (lookahead == ')') ADVANCE(48);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == ':') ADVANCE(49);
      if (lookahead == '>') ADVANCE(51);
      if (lookahead == '}') ADVANCE(42);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(62);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(61);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == 'l') ADVANCE(57);
      if (lookahead == '}') ADVANCE(42);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(53);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(31);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(32);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(20);
      END_STATE();
    case 13:
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 14:
      if (lookahead == 'm') ADVANCE(23);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(52);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(25);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 22:
      if (lookahead == 'p') ADVANCE(19);
      END_STATE();
    case 23:
      if (lookahead == 'p') ADVANCE(21);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(34);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(54);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(45);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(43);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(46);
      END_STATE();
    case 32:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 33:
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 34:
      if (lookahead == 'u') ADVANCE(8);
      END_STATE();
    case 35:
      if (lookahead == 'x') ADVANCE(22);
      END_STATE();
    case 36:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_module);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_export);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_union);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_func);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(62);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 5},
  [13] = {.lex_state = 5},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 5},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 5},
  [24] = {.lex_state = 5},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 1},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 1},
  [95] = {.lex_state = 1},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 1},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 1},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 1},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 1},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 1},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 1},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 1},
  [148] = {.lex_state = 1},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 0},
  [151] = {.lex_state = 1},
  [152] = {.lex_state = 0},
  [153] = {.lex_state = 0},
  [154] = {.lex_state = 0},
  [155] = {.lex_state = 0},
  [156] = {.lex_state = 0},
  [157] = {.lex_state = 1},
  [158] = {.lex_state = 0},
  [159] = {.lex_state = 0},
  [160] = {.lex_state = 0},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_module] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_export] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_union] = ACTIONS(1),
    [anon_sym_func] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(143),
    [sym__item] = STATE(9),
    [sym_module_item] = STATE(142),
    [sym_import_item] = STATE(142),
    [sym_export_item] = STATE(142),
    [sym_struct_item] = STATE(142),
    [sym_union_item] = STATE(142),
    [sym_function_item] = STATE(142),
    [aux_sym_source_file_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_module] = ACTIONS(7),
    [anon_sym_import] = ACTIONS(9),
    [anon_sym_export] = ACTIONS(11),
    [anon_sym_struct] = ACTIONS(13),
    [anon_sym_union] = ACTIONS(15),
    [anon_sym_func] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_module,
    ACTIONS(24), 1,
      anon_sym_import,
    ACTIONS(27), 1,
      anon_sym_export,
    ACTIONS(30), 1,
      anon_sym_struct,
    ACTIONS(33), 1,
      anon_sym_union,
    ACTIONS(36), 1,
      anon_sym_func,
    ACTIONS(19), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(2), 2,
      sym__item,
      aux_sym_source_file_repeat1,
    STATE(142), 6,
      sym_module_item,
      sym_import_item,
      sym_export_item,
      sym_struct_item,
      sym_union_item,
      sym_function_item,
  [38] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_module,
    ACTIONS(9), 1,
      anon_sym_import,
    ACTIONS(11), 1,
      anon_sym_export,
    ACTIONS(13), 1,
      anon_sym_struct,
    ACTIONS(15), 1,
      anon_sym_union,
    ACTIONS(17), 1,
      anon_sym_func,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
    STATE(10), 2,
      sym__item,
      aux_sym_source_file_repeat1,
    STATE(142), 6,
      sym_module_item,
      sym_import_item,
      sym_export_item,
      sym_struct_item,
      sym_union_item,
      sym_function_item,
  [75] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_module,
    ACTIONS(9), 1,
      anon_sym_import,
    ACTIONS(11), 1,
      anon_sym_export,
    ACTIONS(13), 1,
      anon_sym_struct,
    ACTIONS(15), 1,
      anon_sym_union,
    ACTIONS(17), 1,
      anon_sym_func,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    STATE(2), 2,
      sym__item,
      aux_sym_source_file_repeat1,
    STATE(142), 6,
      sym_module_item,
      sym_import_item,
      sym_export_item,
      sym_struct_item,
      sym_union_item,
      sym_function_item,
  [112] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_module,
    ACTIONS(9), 1,
      anon_sym_import,
    ACTIONS(11), 1,
      anon_sym_export,
    ACTIONS(13), 1,
      anon_sym_struct,
    ACTIONS(15), 1,
      anon_sym_union,
    ACTIONS(17), 1,
      anon_sym_func,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    STATE(6), 2,
      sym__item,
      aux_sym_source_file_repeat1,
    STATE(142), 6,
      sym_module_item,
      sym_import_item,
      sym_export_item,
      sym_struct_item,
      sym_union_item,
      sym_function_item,
  [149] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_module,
    ACTIONS(9), 1,
      anon_sym_import,
    ACTIONS(11), 1,
      anon_sym_export,
    ACTIONS(13), 1,
      anon_sym_struct,
    ACTIONS(15), 1,
      anon_sym_union,
    ACTIONS(17), 1,
      anon_sym_func,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    STATE(2), 2,
      sym__item,
      aux_sym_source_file_repeat1,
    STATE(142), 6,
      sym_module_item,
      sym_import_item,
      sym_export_item,
      sym_struct_item,
      sym_union_item,
      sym_function_item,
  [186] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_module,
    ACTIONS(9), 1,
      anon_sym_import,
    ACTIONS(11), 1,
      anon_sym_export,
    ACTIONS(13), 1,
      anon_sym_struct,
    ACTIONS(15), 1,
      anon_sym_union,
    ACTIONS(17), 1,
      anon_sym_func,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
    STATE(4), 2,
      sym__item,
      aux_sym_source_file_repeat1,
    STATE(142), 6,
      sym_module_item,
      sym_import_item,
      sym_export_item,
      sym_struct_item,
      sym_union_item,
      sym_function_item,
  [223] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_module,
    ACTIONS(9), 1,
      anon_sym_import,
    ACTIONS(11), 1,
      anon_sym_export,
    ACTIONS(13), 1,
      anon_sym_struct,
    ACTIONS(15), 1,
      anon_sym_union,
    ACTIONS(17), 1,
      anon_sym_func,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    STATE(2), 2,
      sym__item,
      aux_sym_source_file_repeat1,
    STATE(142), 6,
      sym_module_item,
      sym_import_item,
      sym_export_item,
      sym_struct_item,
      sym_union_item,
      sym_function_item,
  [260] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_module,
    ACTIONS(9), 1,
      anon_sym_import,
    ACTIONS(11), 1,
      anon_sym_export,
    ACTIONS(13), 1,
      anon_sym_struct,
    ACTIONS(15), 1,
      anon_sym_union,
    ACTIONS(17), 1,
      anon_sym_func,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    STATE(2), 2,
      sym__item,
      aux_sym_source_file_repeat1,
    STATE(142), 6,
      sym_module_item,
      sym_import_item,
      sym_export_item,
      sym_struct_item,
      sym_union_item,
      sym_function_item,
  [297] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_module,
    ACTIONS(9), 1,
      anon_sym_import,
    ACTIONS(11), 1,
      anon_sym_export,
    ACTIONS(13), 1,
      anon_sym_struct,
    ACTIONS(15), 1,
      anon_sym_union,
    ACTIONS(17), 1,
      anon_sym_func,
    ACTIONS(53), 1,
      anon_sym_RBRACE,
    STATE(2), 2,
      sym__item,
      aux_sym_source_file_repeat1,
    STATE(142), 6,
      sym_module_item,
      sym_import_item,
      sym_export_item,
      sym_struct_item,
      sym_union_item,
      sym_function_item,
  [334] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_module,
    ACTIONS(9), 1,
      anon_sym_import,
    ACTIONS(11), 1,
      anon_sym_export,
    ACTIONS(13), 1,
      anon_sym_struct,
    ACTIONS(15), 1,
      anon_sym_union,
    ACTIONS(17), 1,
      anon_sym_func,
    ACTIONS(55), 1,
      anon_sym_RBRACE,
    STATE(8), 2,
      sym__item,
      aux_sym_source_file_repeat1,
    STATE(142), 6,
      sym_module_item,
      sym_import_item,
      sym_export_item,
      sym_struct_item,
      sym_union_item,
      sym_function_item,
  [371] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_RBRACE,
    ACTIONS(59), 1,
      anon_sym_let,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(63), 1,
      sym_number,
    STATE(100), 1,
      sym__expression,
    STATE(13), 3,
      sym__statement,
      sym_let_statement,
      aux_sym_block_repeat1,
  [395] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_let,
    ACTIONS(65), 1,
      anon_sym_RBRACE,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(69), 1,
      sym_number,
    STATE(87), 1,
      sym__expression,
    STATE(15), 3,
      sym__statement,
      sym_let_statement,
      aux_sym_block_repeat1,
  [419] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 8,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [433] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    ACTIONS(75), 1,
      anon_sym_let,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(81), 1,
      sym_number,
    STATE(112), 1,
      sym__expression,
    STATE(15), 3,
      sym__statement,
      sym_let_statement,
      aux_sym_block_repeat1,
  [457] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 1,
      anon_sym_RPAREN,
    ACTIONS(86), 1,
      sym_identifier,
    ACTIONS(88), 1,
      sym_number,
    STATE(61), 1,
      sym_func_parameter,
    STATE(153), 1,
      sym__pattern,
  [476] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      sym_identifier,
    ACTIONS(88), 1,
      sym_number,
    ACTIONS(90), 1,
      anon_sym_RPAREN,
    STATE(96), 1,
      sym_func_parameter,
    STATE(153), 1,
      sym__pattern,
  [495] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      sym_identifier,
    ACTIONS(88), 1,
      sym_number,
    ACTIONS(92), 1,
      anon_sym_RPAREN,
    STATE(96), 1,
      sym_func_parameter,
    STATE(153), 1,
      sym__pattern,
  [514] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_RPAREN,
    ACTIONS(96), 1,
      sym_identifier,
    STATE(72), 1,
      sym_struct_parameter,
    STATE(93), 1,
      sym__type,
  [530] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_LPAREN,
    ACTIONS(100), 1,
      anon_sym_LT,
    STATE(102), 1,
      sym_generic_parameter_list,
    STATE(122), 1,
      sym_struct_parameter_list,
  [546] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(102), 1,
      anon_sym_LBRACE,
    STATE(108), 1,
      sym_generic_parameter_list,
    STATE(117), 1,
      sym_union_variant_list,
  [562] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(104), 1,
      anon_sym_LPAREN,
    STATE(37), 1,
      sym_func_parameter_list,
    STATE(109), 1,
      sym_generic_parameter_list,
  [578] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(108), 2,
      anon_sym_let,
      sym_identifier,
  [590] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(112), 2,
      anon_sym_let,
      sym_identifier,
  [602] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      sym_identifier,
    ACTIONS(88), 1,
      sym_number,
    STATE(96), 1,
      sym_func_parameter,
    STATE(153), 1,
      sym__pattern,
  [618] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      sym_identifier,
    ACTIONS(114), 1,
      anon_sym_RPAREN,
    STATE(72), 1,
      sym_struct_parameter,
    STATE(93), 1,
      sym__type,
  [634] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 1,
      anon_sym_COLON,
    STATE(129), 1,
      sym__pattern,
    ACTIONS(118), 2,
      sym_identifier,
      sym_number,
  [648] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_LPAREN,
    STATE(86), 1,
      sym_struct_parameter_list,
    ACTIONS(120), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [662] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      sym_identifier,
    ACTIONS(122), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      sym_struct_parameter,
    STATE(93), 1,
      sym__type,
  [678] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(124), 1,
      anon_sym_DASH_GT,
    ACTIONS(126), 1,
      anon_sym_LBRACE,
    STATE(88), 1,
      sym_generic_parameter_list,
  [694] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(130), 2,
      anon_sym_let,
      sym_identifier,
  [706] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 3,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
  [715] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 1,
      anon_sym_COLON,
    ACTIONS(134), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [726] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_RBRACE,
    ACTIONS(140), 1,
      sym_identifier,
    STATE(57), 1,
      sym_union_variant,
  [739] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 3,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [748] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 3,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
  [757] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      anon_sym_DASH_GT,
    ACTIONS(148), 1,
      anon_sym_LBRACE,
    STATE(116), 1,
      sym_block,
  [770] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      anon_sym_COMMA,
    ACTIONS(153), 1,
      anon_sym_GT,
    STATE(38), 1,
      aux_sym_generic_parameter_list_repeat1,
  [783] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_GT,
    ACTIONS(157), 1,
      sym_identifier,
    STATE(106), 1,
      sym_generic_parameter,
  [796] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 3,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
  [805] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      anon_sym_COLON,
    ACTIONS(161), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [816] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_COMMA,
    ACTIONS(167), 1,
      anon_sym_GT,
    STATE(66), 1,
      aux_sym_generic_parameter_list_repeat1,
  [829] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 3,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
  [838] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 3,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [847] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      sym_identifier,
    STATE(72), 1,
      sym_struct_parameter,
    STATE(93), 1,
      sym__type,
  [860] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_RBRACE,
    ACTIONS(175), 1,
      anon_sym_COMMA,
    STATE(69), 1,
      aux_sym_import_item_repeat1,
  [873] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(89), 1,
      sym__pattern,
    ACTIONS(177), 2,
      sym_identifier,
      sym_number,
  [884] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      anon_sym_RPAREN,
    ACTIONS(179), 1,
      anon_sym_COMMA,
    STATE(68), 1,
      aux_sym_func_parameter_list_repeat1,
  [897] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      anon_sym_RBRACE,
    ACTIONS(183), 1,
      anon_sym_COMMA,
    STATE(69), 1,
      aux_sym_import_item_repeat1,
  [910] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 3,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [919] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_COMMA,
    ACTIONS(190), 1,
      anon_sym_RPAREN,
    STATE(51), 1,
      aux_sym_struct_parameter_list_repeat1,
  [932] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      anon_sym_COMMA,
    ACTIONS(194), 1,
      anon_sym_RPAREN,
    STATE(58), 1,
      aux_sym_struct_parameter_list_repeat1,
  [945] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      sym_identifier,
    ACTIONS(196), 1,
      anon_sym_GT,
    STATE(42), 1,
      sym_generic_parameter,
  [958] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      anon_sym_RBRACE,
    ACTIONS(200), 1,
      anon_sym_COMMA,
    STATE(62), 1,
      aux_sym_union_variant_list_repeat1,
  [971] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      sym_identifier,
    ACTIONS(198), 1,
      anon_sym_RBRACE,
    STATE(105), 1,
      sym_union_variant,
  [984] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      sym_identifier,
    ACTIONS(202), 1,
      anon_sym_RBRACE,
    STATE(105), 1,
      sym_union_variant,
  [997] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      anon_sym_RBRACE,
    ACTIONS(206), 1,
      anon_sym_COMMA,
    STATE(54), 1,
      aux_sym_union_variant_list_repeat1,
  [1010] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_RPAREN,
    ACTIONS(208), 1,
      anon_sym_COMMA,
    STATE(51), 1,
      aux_sym_struct_parameter_list_repeat1,
  [1023] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 3,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1032] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      anon_sym_RBRACE,
    ACTIONS(214), 1,
      anon_sym_COMMA,
    STATE(49), 1,
      aux_sym_import_item_repeat1,
  [1045] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    ACTIONS(218), 1,
      anon_sym_RPAREN,
    STATE(48), 1,
      aux_sym_func_parameter_list_repeat1,
  [1058] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_RBRACE,
    ACTIONS(222), 1,
      anon_sym_COMMA,
    STATE(62), 1,
      aux_sym_union_variant_list_repeat1,
  [1071] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      anon_sym_LBRACE,
    ACTIONS(225), 1,
      anon_sym_DASH_GT,
    STATE(137), 1,
      sym_block,
  [1084] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_RBRACE,
    ACTIONS(229), 1,
      anon_sym_COMMA,
    STATE(46), 1,
      aux_sym_import_item_repeat1,
  [1097] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(156), 1,
      sym__expression,
    ACTIONS(231), 2,
      sym_identifier,
      sym_number,
  [1108] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      anon_sym_COMMA,
    ACTIONS(235), 1,
      anon_sym_GT,
    STATE(38), 1,
      aux_sym_generic_parameter_list_repeat1,
  [1121] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(159), 1,
      sym__expression,
    ACTIONS(237), 2,
      sym_identifier,
      sym_number,
  [1132] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      anon_sym_COMMA,
    ACTIONS(242), 1,
      anon_sym_RPAREN,
    STATE(68), 1,
      aux_sym_func_parameter_list_repeat1,
  [1145] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_RBRACE,
    ACTIONS(246), 1,
      anon_sym_COMMA,
    STATE(69), 1,
      aux_sym_import_item_repeat1,
  [1158] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      sym_identifier,
    ACTIONS(235), 1,
      anon_sym_GT,
    STATE(106), 1,
      sym_generic_parameter,
  [1171] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      anon_sym_RBRACE,
    ACTIONS(251), 1,
      sym_identifier,
  [1181] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1189] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      sym_identifier,
    STATE(155), 1,
      sym__type,
  [1199] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 2,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [1207] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1215] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      sym_identifier,
    STATE(105), 1,
      sym_union_variant,
  [1225] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      anon_sym_RBRACE,
    ACTIONS(261), 1,
      sym_identifier,
  [1235] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1243] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym_identifier,
    ACTIONS(263), 1,
      anon_sym_RBRACE,
  [1253] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      sym_identifier,
    STATE(106), 1,
      sym_generic_parameter,
  [1263] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_RBRACE,
    ACTIONS(267), 1,
      sym_identifier,
  [1273] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      sym_identifier,
    STATE(110), 1,
      sym__type,
  [1283] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      sym_identifier,
    STATE(97), 1,
      sym__type,
  [1293] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      sym_identifier,
    STATE(135), 1,
      sym__type,
  [1303] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 2,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [1311] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1319] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      anon_sym_SEMI,
    ACTIONS(281), 1,
      anon_sym_RBRACE,
  [1329] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_DASH_GT,
    ACTIONS(285), 1,
      anon_sym_LBRACE,
  [1339] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      anon_sym_COLON,
    ACTIONS(289), 1,
      anon_sym_EQ,
  [1349] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      anon_sym_LBRACE,
    STATE(149), 1,
      sym_block,
  [1359] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1367] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 2,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [1375] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1383] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      sym_identifier,
    STATE(91), 1,
      sym__type,
  [1393] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      sym_identifier,
    STATE(90), 1,
      sym__type,
  [1403] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1411] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      anon_sym_LBRACE,
    STATE(130), 1,
      sym_block,
  [1421] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 2,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [1429] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      anon_sym_RBRACE,
    ACTIONS(251), 1,
      sym_identifier,
  [1439] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      anon_sym_SEMI,
    ACTIONS(303), 1,
      anon_sym_RBRACE,
  [1449] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 1,
      sym_identifier,
    STATE(75), 1,
      sym__type,
  [1459] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_LPAREN,
    STATE(128), 1,
      sym_struct_parameter_list,
  [1469] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_RBRACE,
    ACTIONS(251), 1,
      sym_identifier,
  [1479] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [1487] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1495] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [1503] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 1,
      sym_identifier,
    STATE(146), 1,
      sym__type,
  [1513] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_LBRACE,
    STATE(132), 1,
      sym_union_variant_list,
  [1523] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_LPAREN,
    STATE(63), 1,
      sym_func_parameter_list,
  [1533] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1541] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      anon_sym_SEMI,
  [1548] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      anon_sym_SEMI,
  [1555] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 1,
      anon_sym_SEMI,
  [1562] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(317), 1,
      anon_sym_SEMI,
  [1569] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      anon_sym_SEMI,
  [1576] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      anon_sym_SEMI,
  [1583] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      anon_sym_SEMI,
  [1590] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      anon_sym_SEMI,
  [1597] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(327), 1,
      anon_sym_SEMI,
  [1604] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      anon_sym_SEMI,
  [1611] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(331), 1,
      anon_sym_SEMI,
  [1618] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      anon_sym_SEMI,
  [1625] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(335), 1,
      anon_sym_SEMI,
  [1632] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 1,
      anon_sym_SEMI,
  [1639] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 1,
      anon_sym_SEMI,
  [1646] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      anon_sym_SEMI,
  [1653] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 1,
      anon_sym_SEMI,
  [1660] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 1,
      anon_sym_SEMI,
  [1667] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 1,
      anon_sym_COLON,
  [1674] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 1,
      anon_sym_SEMI,
  [1681] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(351), 1,
      anon_sym_SEMI,
  [1688] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      anon_sym_SEMI,
  [1695] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(355), 1,
      anon_sym_SEMI,
  [1702] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(357), 1,
      anon_sym_SEMI,
  [1709] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(359), 1,
      anon_sym_LBRACE,
  [1716] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym_identifier,
  [1723] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(361), 1,
      anon_sym_SEMI,
  [1730] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(363), 1,
      sym_identifier,
  [1737] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(365), 1,
      anon_sym_SEMI,
  [1744] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(367), 1,
      anon_sym_SEMI,
  [1751] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(369), 1,
      anon_sym_SEMI,
  [1758] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(371), 1,
      anon_sym_SEMI,
  [1765] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(373), 1,
      ts_builtin_sym_end,
  [1772] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(375), 1,
      anon_sym_SEMI,
  [1779] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(377), 1,
      anon_sym_SEMI,
  [1786] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(379), 1,
      anon_sym_LBRACE,
  [1793] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(381), 1,
      sym_identifier,
  [1800] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(383), 1,
      sym_identifier,
  [1807] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(385), 1,
      anon_sym_SEMI,
  [1814] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(387), 1,
      anon_sym_SEMI,
  [1821] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(389), 1,
      sym_identifier,
  [1828] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(391), 1,
      anon_sym_SEMI,
  [1835] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(393), 1,
      anon_sym_COLON,
  [1842] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(395), 1,
      anon_sym_SEMI,
  [1849] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(397), 1,
      anon_sym_EQ,
  [1856] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(399), 1,
      anon_sym_SEMI,
  [1863] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(401), 1,
      sym_identifier,
  [1870] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(403), 1,
      anon_sym_LBRACE,
  [1877] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(405), 1,
      anon_sym_SEMI,
  [1884] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(407), 1,
      anon_sym_LBRACE,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 38,
  [SMALL_STATE(4)] = 75,
  [SMALL_STATE(5)] = 112,
  [SMALL_STATE(6)] = 149,
  [SMALL_STATE(7)] = 186,
  [SMALL_STATE(8)] = 223,
  [SMALL_STATE(9)] = 260,
  [SMALL_STATE(10)] = 297,
  [SMALL_STATE(11)] = 334,
  [SMALL_STATE(12)] = 371,
  [SMALL_STATE(13)] = 395,
  [SMALL_STATE(14)] = 419,
  [SMALL_STATE(15)] = 433,
  [SMALL_STATE(16)] = 457,
  [SMALL_STATE(17)] = 476,
  [SMALL_STATE(18)] = 495,
  [SMALL_STATE(19)] = 514,
  [SMALL_STATE(20)] = 530,
  [SMALL_STATE(21)] = 546,
  [SMALL_STATE(22)] = 562,
  [SMALL_STATE(23)] = 578,
  [SMALL_STATE(24)] = 590,
  [SMALL_STATE(25)] = 602,
  [SMALL_STATE(26)] = 618,
  [SMALL_STATE(27)] = 634,
  [SMALL_STATE(28)] = 648,
  [SMALL_STATE(29)] = 662,
  [SMALL_STATE(30)] = 678,
  [SMALL_STATE(31)] = 694,
  [SMALL_STATE(32)] = 706,
  [SMALL_STATE(33)] = 715,
  [SMALL_STATE(34)] = 726,
  [SMALL_STATE(35)] = 739,
  [SMALL_STATE(36)] = 748,
  [SMALL_STATE(37)] = 757,
  [SMALL_STATE(38)] = 770,
  [SMALL_STATE(39)] = 783,
  [SMALL_STATE(40)] = 796,
  [SMALL_STATE(41)] = 805,
  [SMALL_STATE(42)] = 816,
  [SMALL_STATE(43)] = 829,
  [SMALL_STATE(44)] = 838,
  [SMALL_STATE(45)] = 847,
  [SMALL_STATE(46)] = 860,
  [SMALL_STATE(47)] = 873,
  [SMALL_STATE(48)] = 884,
  [SMALL_STATE(49)] = 897,
  [SMALL_STATE(50)] = 910,
  [SMALL_STATE(51)] = 919,
  [SMALL_STATE(52)] = 932,
  [SMALL_STATE(53)] = 945,
  [SMALL_STATE(54)] = 958,
  [SMALL_STATE(55)] = 971,
  [SMALL_STATE(56)] = 984,
  [SMALL_STATE(57)] = 997,
  [SMALL_STATE(58)] = 1010,
  [SMALL_STATE(59)] = 1023,
  [SMALL_STATE(60)] = 1032,
  [SMALL_STATE(61)] = 1045,
  [SMALL_STATE(62)] = 1058,
  [SMALL_STATE(63)] = 1071,
  [SMALL_STATE(64)] = 1084,
  [SMALL_STATE(65)] = 1097,
  [SMALL_STATE(66)] = 1108,
  [SMALL_STATE(67)] = 1121,
  [SMALL_STATE(68)] = 1132,
  [SMALL_STATE(69)] = 1145,
  [SMALL_STATE(70)] = 1158,
  [SMALL_STATE(71)] = 1171,
  [SMALL_STATE(72)] = 1181,
  [SMALL_STATE(73)] = 1189,
  [SMALL_STATE(74)] = 1199,
  [SMALL_STATE(75)] = 1207,
  [SMALL_STATE(76)] = 1215,
  [SMALL_STATE(77)] = 1225,
  [SMALL_STATE(78)] = 1235,
  [SMALL_STATE(79)] = 1243,
  [SMALL_STATE(80)] = 1253,
  [SMALL_STATE(81)] = 1263,
  [SMALL_STATE(82)] = 1273,
  [SMALL_STATE(83)] = 1283,
  [SMALL_STATE(84)] = 1293,
  [SMALL_STATE(85)] = 1303,
  [SMALL_STATE(86)] = 1311,
  [SMALL_STATE(87)] = 1319,
  [SMALL_STATE(88)] = 1329,
  [SMALL_STATE(89)] = 1339,
  [SMALL_STATE(90)] = 1349,
  [SMALL_STATE(91)] = 1359,
  [SMALL_STATE(92)] = 1367,
  [SMALL_STATE(93)] = 1375,
  [SMALL_STATE(94)] = 1383,
  [SMALL_STATE(95)] = 1393,
  [SMALL_STATE(96)] = 1403,
  [SMALL_STATE(97)] = 1411,
  [SMALL_STATE(98)] = 1421,
  [SMALL_STATE(99)] = 1429,
  [SMALL_STATE(100)] = 1439,
  [SMALL_STATE(101)] = 1449,
  [SMALL_STATE(102)] = 1459,
  [SMALL_STATE(103)] = 1469,
  [SMALL_STATE(104)] = 1479,
  [SMALL_STATE(105)] = 1487,
  [SMALL_STATE(106)] = 1495,
  [SMALL_STATE(107)] = 1503,
  [SMALL_STATE(108)] = 1513,
  [SMALL_STATE(109)] = 1523,
  [SMALL_STATE(110)] = 1533,
  [SMALL_STATE(111)] = 1541,
  [SMALL_STATE(112)] = 1548,
  [SMALL_STATE(113)] = 1555,
  [SMALL_STATE(114)] = 1562,
  [SMALL_STATE(115)] = 1569,
  [SMALL_STATE(116)] = 1576,
  [SMALL_STATE(117)] = 1583,
  [SMALL_STATE(118)] = 1590,
  [SMALL_STATE(119)] = 1597,
  [SMALL_STATE(120)] = 1604,
  [SMALL_STATE(121)] = 1611,
  [SMALL_STATE(122)] = 1618,
  [SMALL_STATE(123)] = 1625,
  [SMALL_STATE(124)] = 1632,
  [SMALL_STATE(125)] = 1639,
  [SMALL_STATE(126)] = 1646,
  [SMALL_STATE(127)] = 1653,
  [SMALL_STATE(128)] = 1660,
  [SMALL_STATE(129)] = 1667,
  [SMALL_STATE(130)] = 1674,
  [SMALL_STATE(131)] = 1681,
  [SMALL_STATE(132)] = 1688,
  [SMALL_STATE(133)] = 1695,
  [SMALL_STATE(134)] = 1702,
  [SMALL_STATE(135)] = 1709,
  [SMALL_STATE(136)] = 1716,
  [SMALL_STATE(137)] = 1723,
  [SMALL_STATE(138)] = 1730,
  [SMALL_STATE(139)] = 1737,
  [SMALL_STATE(140)] = 1744,
  [SMALL_STATE(141)] = 1751,
  [SMALL_STATE(142)] = 1758,
  [SMALL_STATE(143)] = 1765,
  [SMALL_STATE(144)] = 1772,
  [SMALL_STATE(145)] = 1779,
  [SMALL_STATE(146)] = 1786,
  [SMALL_STATE(147)] = 1793,
  [SMALL_STATE(148)] = 1800,
  [SMALL_STATE(149)] = 1807,
  [SMALL_STATE(150)] = 1814,
  [SMALL_STATE(151)] = 1821,
  [SMALL_STATE(152)] = 1828,
  [SMALL_STATE(153)] = 1835,
  [SMALL_STATE(154)] = 1842,
  [SMALL_STATE(155)] = 1849,
  [SMALL_STATE(156)] = 1856,
  [SMALL_STATE(157)] = 1863,
  [SMALL_STATE(158)] = 1870,
  [SMALL_STATE(159)] = 1877,
  [SMALL_STATE(160)] = 1884,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(160),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(158),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(157),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(151),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(148),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(138),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(160),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(158),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(157),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(151),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(148),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(154),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(150),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__item, 2),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(47),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(112),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(112),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(153),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 2),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 2),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 5, .production_id = 22),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_statement, 5, .production_id = 22),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__pattern, 1),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_variant, 1, .production_id = 4),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 7, .production_id = 23),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_statement, 7, .production_id = 23),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_parameter_list, 4),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 1),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_parameter_list, 4),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_parameter_list, 3),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [150] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_generic_parameter_list_repeat1, 2), SHIFT_REPEAT(80),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_generic_parameter_list_repeat1, 2),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_parameter_list, 2),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_parameter, 1, .production_id = 4),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(147),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_parameter_list, 5),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_parameter_list, 5),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_parameter_list, 2),
  [187] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_parameter_list_repeat1, 2), SHIFT_REPEAT(45),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_parameter_list_repeat1, 2),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(144),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_parameter_list, 3),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_union_variant_list_repeat1, 2),
  [222] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_union_variant_list_repeat1, 2), SHIFT_REPEAT(76),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(156),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(159),
  [239] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_func_parameter_list_repeat1, 2), SHIFT_REPEAT(25),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_func_parameter_list_repeat1, 2),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_import_item_repeat1, 2),
  [246] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_import_item_repeat1, 2), SHIFT_REPEAT(136),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(155),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_parameter_list, 5),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_parameter, 4, .production_id = 19),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_parameter_list, 2),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_variant, 2, .production_id = 10),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(152),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_parameter, 3, .production_id = 15),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_parameter_list, 3),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_parameter, 1, .production_id = 5),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_parameter_list, 4),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_parameter, 3, .production_id = 13),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(146),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_parameter, 3, .production_id = 14),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_variant_list, 3),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_item, 6),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_item, 6, .production_id = 9),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_item, 6),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_item, 4, .production_id = 8),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_item, 3, .production_id = 2),
  [325] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_item, 4, .production_id = 3),
  [327] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_variant_list, 4),
  [329] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_item, 4),
  [331] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_item, 6, .production_id = 12),
  [333] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_item, 3, .production_id = 1),
  [335] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_item, 4),
  [337] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [339] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_item, 7, .production_id = 12),
  [341] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_item, 3),
  [343] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_item, 3),
  [345] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_item, 4, .production_id = 6),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [349] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_item, 6, .production_id = 16),
  [351] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_variant_list, 2),
  [353] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_item, 4, .production_id = 7),
  [355] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, .production_id = 17),
  [357] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [361] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_item, 5, .production_id = 11),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [365] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_item, 5),
  [367] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_item, 7, .production_id = 18),
  [369] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_item, 5),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [373] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [375] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_variant_list, 5),
  [377] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_item, 5, .production_id = 9),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [385] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_item, 7, .production_id = 20),
  [387] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_item, 5, .production_id = 3),
  [389] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [391] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, .production_id = 21),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [395] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_item, 8, .production_id = 18),
  [397] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [399] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [401] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [403] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [405] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [407] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_language_test(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const uint16_t *)ts_parse_table,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .field_count = FIELD_COUNT,
    .field_map_slices = (const TSFieldMapSlice *)ts_field_map_slices,
    .field_map_entries = (const TSFieldMapEntry *)ts_field_map_entries,
    .field_names = ts_field_names,
    .large_state_count = LARGE_STATE_COUNT,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .state_count = STATE_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
