#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 12
#define STATE_COUNT 208
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 58
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 12
#define MAX_ALIAS_SEQUENCE_LENGTH 8

enum {
  anon_sym_SEMI = 1,
  anon_sym_module = 2,
  anon_sym_DASH_GT = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  anon_sym_COLON_COLON = 6,
  anon_sym_COMMA = 7,
  anon_sym_as = 8,
  anon_sym_import = 9,
  anon_sym_export = 10,
  anon_sym_struct = 11,
  anon_sym_LPAREN = 12,
  anon_sym_RPAREN = 13,
  anon_sym_COLON = 14,
  anon_sym_LT = 15,
  anon_sym_GT = 16,
  anon_sym_union = 17,
  anon_sym_func = 18,
  anon_sym_let = 19,
  anon_sym_EQ = 20,
  sym_identifier = 21,
  sym_number = 22,
  sym_comment = 23,
  sym_source_file = 24,
  sym__item = 25,
  sym_module_item = 26,
  sym_simple_path = 27,
  sym_compound_path = 28,
  sym_import_item = 29,
  sym_export_item = 30,
  sym_struct_item = 31,
  sym_struct_parameter_list = 32,
  sym_struct_parameter = 33,
  sym_generic_argument_list = 34,
  sym_generic_parameter_list = 35,
  sym_generic_parameter = 36,
  sym_union_item = 37,
  sym_union_variant_list = 38,
  sym_union_variant = 39,
  sym_function_item = 40,
  sym_func_parameter_list = 41,
  sym_func_parameter = 42,
  sym__type = 43,
  sym_block = 44,
  sym__statement = 45,
  sym_let_statement = 46,
  sym__expression = 47,
  sym__pattern = 48,
  aux_sym_source_file_repeat1 = 49,
  aux_sym_compound_path_repeat1 = 50,
  aux_sym_export_item_repeat1 = 51,
  aux_sym_struct_parameter_list_repeat1 = 52,
  aux_sym_generic_argument_list_repeat1 = 53,
  aux_sym_generic_parameter_list_repeat1 = 54,
  aux_sym_union_variant_list_repeat1 = 55,
  aux_sym_func_parameter_list_repeat1 = 56,
  aux_sym_block_repeat1 = 57,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_module] = "module",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_COMMA] = ",",
  [anon_sym_as] = "as",
  [anon_sym_import] = "import",
  [anon_sym_export] = "export",
  [anon_sym_struct] = "struct",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_union] = "union",
  [anon_sym_func] = "func",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__item] = "_item",
  [sym_module_item] = "module_item",
  [sym_simple_path] = "simple_path",
  [sym_compound_path] = "compound_path",
  [sym_import_item] = "import_item",
  [sym_export_item] = "export_item",
  [sym_struct_item] = "struct_item",
  [sym_struct_parameter_list] = "struct_parameter_list",
  [sym_struct_parameter] = "struct_parameter",
  [sym_generic_argument_list] = "generic_argument_list",
  [sym_generic_parameter_list] = "generic_parameter_list",
  [sym_generic_parameter] = "generic_parameter",
  [sym_union_item] = "union_item",
  [sym_union_variant_list] = "union_variant_list",
  [sym_union_variant] = "union_variant",
  [sym_function_item] = "function_item",
  [sym_func_parameter_list] = "func_parameter_list",
  [sym_func_parameter] = "func_parameter",
  [sym__type] = "_type",
  [sym_block] = "block",
  [sym__statement] = "_statement",
  [sym_let_statement] = "let_statement",
  [sym__expression] = "_expression",
  [sym__pattern] = "_pattern",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_compound_path_repeat1] = "compound_path_repeat1",
  [aux_sym_export_item_repeat1] = "export_item_repeat1",
  [aux_sym_struct_parameter_list_repeat1] = "struct_parameter_list_repeat1",
  [aux_sym_generic_argument_list_repeat1] = "generic_argument_list_repeat1",
  [aux_sym_generic_parameter_list_repeat1] = "generic_parameter_list_repeat1",
  [aux_sym_union_variant_list_repeat1] = "union_variant_list_repeat1",
  [aux_sym_func_parameter_list_repeat1] = "func_parameter_list_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_module] = anon_sym_module,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_export] = anon_sym_export,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_union] = anon_sym_union,
  [anon_sym_func] = anon_sym_func,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__item] = sym__item,
  [sym_module_item] = sym_module_item,
  [sym_simple_path] = sym_simple_path,
  [sym_compound_path] = sym_compound_path,
  [sym_import_item] = sym_import_item,
  [sym_export_item] = sym_export_item,
  [sym_struct_item] = sym_struct_item,
  [sym_struct_parameter_list] = sym_struct_parameter_list,
  [sym_struct_parameter] = sym_struct_parameter,
  [sym_generic_argument_list] = sym_generic_argument_list,
  [sym_generic_parameter_list] = sym_generic_parameter_list,
  [sym_generic_parameter] = sym_generic_parameter,
  [sym_union_item] = sym_union_item,
  [sym_union_variant_list] = sym_union_variant_list,
  [sym_union_variant] = sym_union_variant,
  [sym_function_item] = sym_function_item,
  [sym_func_parameter_list] = sym_func_parameter_list,
  [sym_func_parameter] = sym_func_parameter,
  [sym__type] = sym__type,
  [sym_block] = sym_block,
  [sym__statement] = sym__statement,
  [sym_let_statement] = sym_let_statement,
  [sym__expression] = sym__expression,
  [sym__pattern] = sym__pattern,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_compound_path_repeat1] = aux_sym_compound_path_repeat1,
  [aux_sym_export_item_repeat1] = aux_sym_export_item_repeat1,
  [aux_sym_struct_parameter_list_repeat1] = aux_sym_struct_parameter_list_repeat1,
  [aux_sym_generic_argument_list_repeat1] = aux_sym_generic_argument_list_repeat1,
  [aux_sym_generic_parameter_list_repeat1] = aux_sym_generic_parameter_list_repeat1,
  [aux_sym_union_variant_list_repeat1] = aux_sym_union_variant_list_repeat1,
  [aux_sym_func_parameter_list_repeat1] = aux_sym_func_parameter_list_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_module] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_export] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_union] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_func] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_module_item] = {
    .visible = true,
    .named = true,
  },
  [sym_simple_path] = {
    .visible = true,
    .named = true,
  },
  [sym_compound_path] = {
    .visible = true,
    .named = true,
  },
  [sym_import_item] = {
    .visible = true,
    .named = true,
  },
  [sym_export_item] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_item] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_generic_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_generic_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_generic_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_union_item] = {
    .visible = true,
    .named = true,
  },
  [sym_union_variant_list] = {
    .visible = true,
    .named = true,
  },
  [sym_union_variant] = {
    .visible = true,
    .named = true,
  },
  [sym_function_item] = {
    .visible = true,
    .named = true,
  },
  [sym_func_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_func_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_let_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__pattern] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_compound_path_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_export_item_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_generic_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_generic_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_union_variant_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_func_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_args = 1,
  field_body = 2,
  field_bounds = 3,
  field_generics = 4,
  field_name = 5,
  field_parameters = 6,
  field_pattern = 7,
  field_return_type = 8,
  field_trailing = 9,
  field_type = 10,
  field_value = 11,
  field_variants = 12,
};

static const char *ts_field_names[] = {
  [0] = NULL,
  [field_args] = "args",
  [field_body] = "body",
  [field_bounds] = "bounds",
  [field_generics] = "generics",
  [field_name] = "name",
  [field_parameters] = "parameters",
  [field_pattern] = "pattern",
  [field_return_type] = "return_type",
  [field_trailing] = "trailing",
  [field_type] = "type",
  [field_value] = "value",
  [field_variants] = "variants",
};

static const TSFieldMapSlice ts_field_map_slices[25] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 1},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 1},
  [6] = {.index = 7, .length = 1},
  [7] = {.index = 8, .length = 3},
  [8] = {.index = 11, .length = 3},
  [9] = {.index = 14, .length = 3},
  [10] = {.index = 17, .length = 2},
  [11] = {.index = 19, .length = 2},
  [12] = {.index = 21, .length = 4},
  [13] = {.index = 25, .length = 2},
  [14] = {.index = 27, .length = 2},
  [15] = {.index = 29, .length = 2},
  [16] = {.index = 31, .length = 2},
  [17] = {.index = 33, .length = 4},
  [18] = {.index = 37, .length = 1},
  [19] = {.index = 38, .length = 3},
  [20] = {.index = 41, .length = 3},
  [21] = {.index = 44, .length = 5},
  [22] = {.index = 49, .length = 1},
  [23] = {.index = 50, .length = 2},
  [24] = {.index = 52, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
    {field_parameters, 2},
  [2] =
    {field_name, 1},
    {field_variants, 2},
  [4] =
    {field_name, 1},
  [5] =
    {field_name, 0},
  [6] =
    {field_args, 1},
  [7] =
    {field_type, 0},
  [8] =
    {field_generics, 2},
    {field_name, 1},
    {field_parameters, 3},
  [11] =
    {field_generics, 2},
    {field_name, 1},
    {field_variants, 3},
  [14] =
    {field_body, 3},
    {field_name, 1},
    {field_parameters, 2},
  [17] =
    {field_generics, 2},
    {field_name, 1},
  [19] =
    {field_name, 0},
    {field_parameters, 1},
  [21] =
    {field_body, 4},
    {field_generics, 2},
    {field_name, 1},
    {field_parameters, 3},
  [25] =
    {field_name, 1},
    {field_return_type, 3},
  [27] =
    {field_bounds, 2},
    {field_name, 0},
  [29] =
    {field_name, 0},
    {field_type, 2},
  [31] =
    {field_pattern, 0},
    {field_type, 2},
  [33] =
    {field_body, 5},
    {field_name, 1},
    {field_parameters, 2},
    {field_return_type, 4},
  [37] =
    {field_trailing, 1},
  [38] =
    {field_generics, 2},
    {field_name, 1},
    {field_return_type, 4},
  [41] =
    {field_name, 0},
    {field_pattern, 1},
    {field_type, 3},
  [44] =
    {field_body, 6},
    {field_generics, 2},
    {field_name, 1},
    {field_parameters, 3},
    {field_return_type, 5},
  [49] =
    {field_trailing, 2},
  [50] =
    {field_name, 1},
    {field_value, 3},
  [52] =
    {field_name, 1},
    {field_type, 2},
    {field_type, 3},
    {field_value, 5},
};

static TSSymbol ts_alias_sequences[25][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(38);
      if (lookahead == '(') ADVANCE(50);
      if (lookahead == ')') ADVANCE(51);
      if (lookahead == '+') ADVANCE(37);
      if (lookahead == ',') ADVANCE(45);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == ':') ADVANCE(53);
      if (lookahead == ';') ADVANCE(39);
      if (lookahead == '<') ADVANCE(54);
      if (lookahead == '=') ADVANCE(60);
      if (lookahead == '>') ADVANCE(55);
      if (lookahead == 'a') ADVANCE(27);
      if (lookahead == 'e') ADVANCE(36);
      if (lookahead == 'f') ADVANCE(34);
      if (lookahead == 'i') ADVANCE(14);
      if (lookahead == 'l') ADVANCE(11);
      if (lookahead == 'm') ADVANCE(18);
      if (lookahead == 's') ADVANCE(28);
      if (lookahead == 'u') ADVANCE(15);
      if (lookahead == '{') ADVANCE(42);
      if (lookahead == '}') ADVANCE(43);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 1:
      if (lookahead == ')') ADVANCE(51);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == ':') ADVANCE(52);
      if (lookahead == '>') ADVANCE(55);
      if (lookahead == '{') ADVANCE(42);
      if (lookahead == '}') ADVANCE(43);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(66);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(65);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == 'l') ADVANCE(61);
      if (lookahead == '}') ADVANCE(43);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(57);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(32);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(33);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(20);
      END_STATE();
    case 13:
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 14:
      if (lookahead == 'm') ADVANCE(23);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(56);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(25);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 22:
      if (lookahead == 'p') ADVANCE(19);
      END_STATE();
    case 23:
      if (lookahead == 'p') ADVANCE(21);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(35);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(46);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(58);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(48);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(47);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(49);
      END_STATE();
    case 33:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 34:
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 35:
      if (lookahead == 'u') ADVANCE(8);
      END_STATE();
    case 36:
      if (lookahead == 'x') ADVANCE(22);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_module);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_export);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(44);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_union);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_func);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 5},
  [14] = {.lex_state = 5},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 5},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 5},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 5},
  [45] = {.lex_state = 5},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 1},
  [85] = {.lex_state = 1},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 1},
  [92] = {.lex_state = 1},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 1},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 1},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 1},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 1},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 1},
  [105] = {.lex_state = 1},
  [106] = {.lex_state = 1},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 1},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 1},
  [111] = {.lex_state = 1},
  [112] = {.lex_state = 1},
  [113] = {.lex_state = 1},
  [114] = {.lex_state = 1},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 1},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 1},
  [137] = {.lex_state = 1},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 1},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 1},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 1},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 1},
  [151] = {.lex_state = 0},
  [152] = {.lex_state = 0},
  [153] = {.lex_state = 0},
  [154] = {.lex_state = 0},
  [155] = {.lex_state = 0},
  [156] = {.lex_state = 0},
  [157] = {.lex_state = 0},
  [158] = {.lex_state = 0},
  [159] = {.lex_state = 1},
  [160] = {.lex_state = 0},
  [161] = {.lex_state = 0},
  [162] = {.lex_state = 0},
  [163] = {.lex_state = 0},
  [164] = {.lex_state = 0},
  [165] = {.lex_state = 0},
  [166] = {.lex_state = 0},
  [167] = {.lex_state = 0},
  [168] = {.lex_state = 0},
  [169] = {.lex_state = 0},
  [170] = {.lex_state = 0},
  [171] = {.lex_state = 0},
  [172] = {.lex_state = 1},
  [173] = {.lex_state = 0},
  [174] = {.lex_state = 0},
  [175] = {.lex_state = 0},
  [176] = {.lex_state = 0},
  [177] = {.lex_state = 0},
  [178] = {.lex_state = 0},
  [179] = {.lex_state = 0},
  [180] = {.lex_state = 0},
  [181] = {.lex_state = 0},
  [182] = {.lex_state = 0},
  [183] = {.lex_state = 0},
  [184] = {.lex_state = 0},
  [185] = {.lex_state = 0},
  [186] = {.lex_state = 0},
  [187] = {.lex_state = 0},
  [188] = {.lex_state = 0},
  [189] = {.lex_state = 0},
  [190] = {.lex_state = 0},
  [191] = {.lex_state = 0},
  [192] = {.lex_state = 0},
  [193] = {.lex_state = 0},
  [194] = {.lex_state = 0},
  [195] = {.lex_state = 0},
  [196] = {.lex_state = 1},
  [197] = {.lex_state = 1},
  [198] = {.lex_state = 0},
  [199] = {.lex_state = 0},
  [200] = {.lex_state = 0},
  [201] = {.lex_state = 1},
  [202] = {.lex_state = 1},
  [203] = {.lex_state = 0},
  [204] = {.lex_state = 0},
  [205] = {.lex_state = 0},
  [206] = {.lex_state = 0},
  [207] = {.lex_state = 0},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_module] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_export] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_union] = ACTIONS(1),
    [anon_sym_func] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(194),
    [sym__item] = STATE(3),
    [sym_module_item] = STATE(193),
    [sym_import_item] = STATE(193),
    [sym_export_item] = STATE(193),
    [sym_struct_item] = STATE(193),
    [sym_union_item] = STATE(193),
    [sym_function_item] = STATE(193),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_module] = ACTIONS(7),
    [anon_sym_import] = ACTIONS(9),
    [anon_sym_export] = ACTIONS(11),
    [anon_sym_struct] = ACTIONS(13),
    [anon_sym_union] = ACTIONS(15),
    [anon_sym_func] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_module,
    ACTIONS(24), 1,
      anon_sym_import,
    ACTIONS(27), 1,
      anon_sym_export,
    ACTIONS(30), 1,
      anon_sym_struct,
    ACTIONS(33), 1,
      anon_sym_union,
    ACTIONS(36), 1,
      anon_sym_func,
    ACTIONS(19), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(2), 2,
      sym__item,
      aux_sym_source_file_repeat1,
    STATE(193), 6,
      sym_module_item,
      sym_import_item,
      sym_export_item,
      sym_struct_item,
      sym_union_item,
      sym_function_item,
  [38] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_module,
    ACTIONS(9), 1,
      anon_sym_import,
    ACTIONS(11), 1,
      anon_sym_export,
    ACTIONS(13), 1,
      anon_sym_struct,
    ACTIONS(15), 1,
      anon_sym_union,
    ACTIONS(17), 1,
      anon_sym_func,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    STATE(2), 2,
      sym__item,
      aux_sym_source_file_repeat1,
    STATE(193), 6,
      sym_module_item,
      sym_import_item,
      sym_export_item,
      sym_struct_item,
      sym_union_item,
      sym_function_item,
  [75] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_module,
    ACTIONS(9), 1,
      anon_sym_import,
    ACTIONS(11), 1,
      anon_sym_export,
    ACTIONS(13), 1,
      anon_sym_struct,
    ACTIONS(15), 1,
      anon_sym_union,
    ACTIONS(17), 1,
      anon_sym_func,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    STATE(2), 2,
      sym__item,
      aux_sym_source_file_repeat1,
    STATE(193), 6,
      sym_module_item,
      sym_import_item,
      sym_export_item,
      sym_struct_item,
      sym_union_item,
      sym_function_item,
  [112] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_module,
    ACTIONS(9), 1,
      anon_sym_import,
    ACTIONS(11), 1,
      anon_sym_export,
    ACTIONS(13), 1,
      anon_sym_struct,
    ACTIONS(15), 1,
      anon_sym_union,
    ACTIONS(17), 1,
      anon_sym_func,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    STATE(4), 2,
      sym__item,
      aux_sym_source_file_repeat1,
    STATE(193), 6,
      sym_module_item,
      sym_import_item,
      sym_export_item,
      sym_struct_item,
      sym_union_item,
      sym_function_item,
  [149] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_module,
    ACTIONS(9), 1,
      anon_sym_import,
    ACTIONS(11), 1,
      anon_sym_export,
    ACTIONS(13), 1,
      anon_sym_struct,
    ACTIONS(15), 1,
      anon_sym_union,
    ACTIONS(17), 1,
      anon_sym_func,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    STATE(2), 2,
      sym__item,
      aux_sym_source_file_repeat1,
    STATE(193), 6,
      sym_module_item,
      sym_import_item,
      sym_export_item,
      sym_struct_item,
      sym_union_item,
      sym_function_item,
  [186] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_module,
    ACTIONS(9), 1,
      anon_sym_import,
    ACTIONS(11), 1,
      anon_sym_export,
    ACTIONS(13), 1,
      anon_sym_struct,
    ACTIONS(15), 1,
      anon_sym_union,
    ACTIONS(17), 1,
      anon_sym_func,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
    STATE(2), 2,
      sym__item,
      aux_sym_source_file_repeat1,
    STATE(193), 6,
      sym_module_item,
      sym_import_item,
      sym_export_item,
      sym_struct_item,
      sym_union_item,
      sym_function_item,
  [223] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_module,
    ACTIONS(9), 1,
      anon_sym_import,
    ACTIONS(11), 1,
      anon_sym_export,
    ACTIONS(13), 1,
      anon_sym_struct,
    ACTIONS(15), 1,
      anon_sym_union,
    ACTIONS(17), 1,
      anon_sym_func,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    STATE(7), 2,
      sym__item,
      aux_sym_source_file_repeat1,
    STATE(193), 6,
      sym_module_item,
      sym_import_item,
      sym_export_item,
      sym_struct_item,
      sym_union_item,
      sym_function_item,
  [260] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_module,
    ACTIONS(9), 1,
      anon_sym_import,
    ACTIONS(11), 1,
      anon_sym_export,
    ACTIONS(13), 1,
      anon_sym_struct,
    ACTIONS(15), 1,
      anon_sym_union,
    ACTIONS(17), 1,
      anon_sym_func,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    STATE(2), 2,
      sym__item,
      aux_sym_source_file_repeat1,
    STATE(193), 6,
      sym_module_item,
      sym_import_item,
      sym_export_item,
      sym_struct_item,
      sym_union_item,
      sym_function_item,
  [297] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_module,
    ACTIONS(9), 1,
      anon_sym_import,
    ACTIONS(11), 1,
      anon_sym_export,
    ACTIONS(13), 1,
      anon_sym_struct,
    ACTIONS(15), 1,
      anon_sym_union,
    ACTIONS(17), 1,
      anon_sym_func,
    ACTIONS(53), 1,
      anon_sym_RBRACE,
    STATE(9), 2,
      sym__item,
      aux_sym_source_file_repeat1,
    STATE(193), 6,
      sym_module_item,
      sym_import_item,
      sym_export_item,
      sym_struct_item,
      sym_union_item,
      sym_function_item,
  [334] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_module,
    ACTIONS(9), 1,
      anon_sym_import,
    ACTIONS(11), 1,
      anon_sym_export,
    ACTIONS(13), 1,
      anon_sym_struct,
    ACTIONS(15), 1,
      anon_sym_union,
    ACTIONS(17), 1,
      anon_sym_func,
    ACTIONS(55), 1,
      anon_sym_RBRACE,
    STATE(6), 2,
      sym__item,
      aux_sym_source_file_repeat1,
    STATE(193), 6,
      sym_module_item,
      sym_import_item,
      sym_export_item,
      sym_struct_item,
      sym_union_item,
      sym_function_item,
  [371] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_COLON_COLON,
    ACTIONS(61), 1,
      anon_sym_LT,
    STATE(20), 1,
      sym_generic_argument_list,
    ACTIONS(57), 7,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_EQ,
  [393] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      anon_sym_RBRACE,
    ACTIONS(65), 1,
      anon_sym_let,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(69), 1,
      sym_number,
    STATE(157), 2,
      sym_simple_path,
      sym__expression,
    STATE(16), 3,
      sym__statement,
      sym_let_statement,
      aux_sym_block_repeat1,
  [418] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_let,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(71), 1,
      anon_sym_RBRACE,
    ACTIONS(73), 1,
      sym_number,
    STATE(118), 2,
      sym_simple_path,
      sym__expression,
    STATE(13), 3,
      sym__statement,
      sym_let_statement,
      aux_sym_block_repeat1,
  [443] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 9,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON_COLON,
      anon_sym_COMMA,
      anon_sym_as,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_EQ,
  [458] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_RBRACE,
    ACTIONS(79), 1,
      anon_sym_let,
    ACTIONS(82), 1,
      sym_identifier,
    ACTIONS(85), 1,
      sym_number,
    STATE(189), 2,
      sym_simple_path,
      sym__expression,
    STATE(16), 3,
      sym__statement,
      sym_let_statement,
      aux_sym_block_repeat1,
  [483] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 9,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON_COLON,
      anon_sym_COMMA,
      anon_sym_as,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_EQ,
  [498] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 9,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON_COLON,
      anon_sym_COMMA,
      anon_sym_as,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_EQ,
  [513] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 9,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON_COLON,
      anon_sym_COMMA,
      anon_sym_as,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_EQ,
  [528] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_COLON_COLON,
    ACTIONS(94), 7,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_EQ,
  [544] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 8,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_export,
      anon_sym_struct,
      anon_sym_union,
      anon_sym_func,
  [558] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 7,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_EQ,
  [571] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 7,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_EQ,
  [584] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      anon_sym_LT,
    ACTIONS(106), 1,
      anon_sym_COLON_COLON,
    ACTIONS(108), 1,
      anon_sym_as,
    STATE(37), 1,
      sym_generic_argument_list,
    ACTIONS(104), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [604] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_COLON_COLON,
    ACTIONS(61), 1,
      anon_sym_LT,
    ACTIONS(110), 1,
      anon_sym_COLON,
    STATE(20), 1,
      sym_generic_argument_list,
    ACTIONS(57), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [624] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      anon_sym_RPAREN,
    ACTIONS(114), 1,
      sym_identifier,
    STATE(143), 1,
      sym_struct_parameter,
    STATE(154), 2,
      sym_simple_path,
      sym__type,
  [641] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 1,
      anon_sym_RPAREN,
    ACTIONS(118), 1,
      sym_identifier,
    ACTIONS(120), 1,
      sym_number,
    STATE(152), 1,
      sym_func_parameter,
    STATE(169), 1,
      sym__pattern,
  [660] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      sym_identifier,
    ACTIONS(122), 1,
      anon_sym_RPAREN,
    STATE(143), 1,
      sym_struct_parameter,
    STATE(154), 2,
      sym_simple_path,
      sym__type,
  [677] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      sym_identifier,
    ACTIONS(124), 1,
      anon_sym_RPAREN,
    STATE(60), 1,
      sym_struct_parameter,
    STATE(154), 2,
      sym_simple_path,
      sym__type,
  [694] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      sym_identifier,
    ACTIONS(120), 1,
      sym_number,
    ACTIONS(126), 1,
      anon_sym_RPAREN,
    STATE(152), 1,
      sym_func_parameter,
    STATE(169), 1,
      sym__pattern,
  [713] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      sym_identifier,
    ACTIONS(120), 1,
      sym_number,
    ACTIONS(128), 1,
      anon_sym_RPAREN,
    STATE(69), 1,
      sym_func_parameter,
    STATE(169), 1,
      sym__pattern,
  [732] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      sym_identifier,
    STATE(143), 1,
      sym_struct_parameter,
    STATE(154), 2,
      sym_simple_path,
      sym__type,
  [746] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_GT,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(146), 2,
      sym_simple_path,
      sym__type,
  [760] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      sym_identifier,
    ACTIONS(120), 1,
      sym_number,
    STATE(152), 1,
      sym_func_parameter,
    STATE(169), 1,
      sym__pattern,
  [776] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      anon_sym_DASH_GT,
    ACTIONS(136), 1,
      anon_sym_LBRACE,
    ACTIONS(138), 1,
      anon_sym_LT,
    STATE(120), 1,
      sym_generic_parameter_list,
  [792] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      anon_sym_COLON,
    STATE(162), 1,
      sym__pattern,
    ACTIONS(142), 2,
      sym_identifier,
      sym_number,
  [806] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      anon_sym_COLON_COLON,
    ACTIONS(148), 1,
      anon_sym_as,
    ACTIONS(144), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [820] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    ACTIONS(150), 1,
      anon_sym_GT,
    STATE(146), 2,
      sym_simple_path,
      sym__type,
  [834] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_LT,
    ACTIONS(152), 1,
      anon_sym_LPAREN,
    STATE(68), 1,
      sym_func_parameter_list,
    STATE(142), 1,
      sym_generic_parameter_list,
  [850] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_LT,
    ACTIONS(154), 1,
      anon_sym_LBRACE,
    STATE(139), 1,
      sym_generic_parameter_list,
    STATE(178), 1,
      sym_union_variant_list,
  [866] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      anon_sym_LPAREN,
    STATE(115), 1,
      sym_struct_parameter_list,
    ACTIONS(156), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [880] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(162), 2,
      anon_sym_let,
      sym_identifier,
  [892] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    ACTIONS(164), 1,
      sym_number,
    STATE(206), 2,
      sym_simple_path,
      sym__expression,
  [906] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(168), 2,
      anon_sym_let,
      sym_identifier,
  [918] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(172), 2,
      anon_sym_let,
      sym_identifier,
  [930] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_LT,
    ACTIONS(158), 1,
      anon_sym_LPAREN,
    STATE(130), 1,
      sym_generic_parameter_list,
    STATE(186), 1,
      sym_struct_parameter_list,
  [946] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    ACTIONS(174), 1,
      sym_number,
    STATE(199), 2,
      sym_simple_path,
      sym__expression,
  [960] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    ACTIONS(176), 1,
      anon_sym_GT,
    STATE(87), 2,
      sym_simple_path,
      sym__type,
  [974] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    ACTIONS(178), 1,
      anon_sym_RBRACE,
    STATE(127), 1,
      sym_simple_path,
  [987] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      anon_sym_RBRACE,
    ACTIONS(182), 1,
      sym_identifier,
    STATE(65), 1,
      sym_union_variant,
  [1000] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      anon_sym_LBRACE,
    ACTIONS(186), 1,
      sym_identifier,
    STATE(138), 1,
      sym_compound_path,
  [1013] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_RBRACE,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    STATE(93), 1,
      aux_sym_compound_path_repeat1,
  [1026] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      sym_identifier,
    ACTIONS(188), 1,
      anon_sym_RBRACE,
    STATE(132), 1,
      sym_compound_path,
  [1039] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      sym_identifier,
    ACTIONS(192), 1,
      anon_sym_RBRACE,
    STATE(132), 1,
      sym_compound_path,
  [1052] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      anon_sym_RBRACE,
    ACTIONS(194), 1,
      anon_sym_COMMA,
    STATE(93), 1,
      aux_sym_compound_path_repeat1,
  [1065] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 3,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
  [1074] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 3,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
  [1083] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_RBRACE,
    ACTIONS(200), 1,
      anon_sym_COMMA,
    STATE(99), 1,
      aux_sym_export_item_repeat1,
  [1096] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 3,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1105] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      anon_sym_COMMA,
    ACTIONS(206), 1,
      anon_sym_RPAREN,
    STATE(103), 1,
      aux_sym_struct_parameter_list_repeat1,
  [1118] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      sym_identifier,
    ACTIONS(208), 1,
      anon_sym_RBRACE,
    STATE(90), 1,
      sym_compound_path,
  [1131] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_COMMA,
    ACTIONS(212), 1,
      anon_sym_GT,
    STATE(80), 1,
      aux_sym_generic_parameter_list_repeat1,
  [1144] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_COMMA,
    ACTIONS(217), 1,
      anon_sym_RPAREN,
    STATE(63), 1,
      aux_sym_func_parameter_list_repeat1,
  [1157] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_COLON,
    ACTIONS(219), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [1168] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      anon_sym_RBRACE,
    ACTIONS(225), 1,
      anon_sym_COMMA,
    STATE(107), 1,
      aux_sym_union_variant_list_repeat1,
  [1181] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 3,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
  [1190] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(134), 2,
      sym_simple_path,
      sym__type,
  [1201] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      anon_sym_DASH_GT,
    ACTIONS(231), 1,
      anon_sym_LBRACE,
    STATE(170), 1,
      sym_block,
  [1214] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      anon_sym_COMMA,
    ACTIONS(235), 1,
      anon_sym_RPAREN,
    STATE(109), 1,
      aux_sym_func_parameter_list_repeat1,
  [1227] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_RBRACE,
    ACTIONS(239), 1,
      anon_sym_COMMA,
    STATE(70), 1,
      aux_sym_union_variant_list_repeat1,
  [1240] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_LBRACE,
    ACTIONS(242), 1,
      anon_sym_DASH_GT,
    STATE(203), 1,
      sym_block,
  [1253] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(123), 2,
      sym_simple_path,
      sym__type,
  [1264] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_COMMA,
    ACTIONS(247), 1,
      anon_sym_GT,
    STATE(73), 1,
      aux_sym_generic_argument_list_repeat1,
  [1277] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      sym_identifier,
    ACTIONS(249), 1,
      anon_sym_RBRACE,
    STATE(147), 1,
      sym_union_variant,
  [1290] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      anon_sym_RBRACE,
    ACTIONS(253), 1,
      anon_sym_COMMA,
    STATE(101), 1,
      aux_sym_compound_path_repeat1,
  [1303] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      anon_sym_COMMA,
    ACTIONS(258), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      aux_sym_struct_parameter_list_repeat1,
  [1316] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 3,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1325] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      anon_sym_GT,
    ACTIONS(264), 1,
      sym_identifier,
    STATE(124), 1,
      sym_generic_parameter,
  [1338] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 3,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
  [1347] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      anon_sym_GT,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    STATE(97), 1,
      aux_sym_generic_parameter_list_repeat1,
  [1360] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 3,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1369] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(177), 2,
      sym_simple_path,
      sym__type,
  [1380] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      anon_sym_RBRACE,
    ACTIONS(274), 1,
      anon_sym_COMMA,
    STATE(58), 1,
      aux_sym_export_item_repeat1,
  [1393] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      sym_identifier,
    ACTIONS(276), 1,
      anon_sym_RBRACE,
    STATE(95), 1,
      sym_compound_path,
  [1406] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      sym_identifier,
    ACTIONS(278), 1,
      anon_sym_RBRACE,
    STATE(75), 1,
      sym_compound_path,
  [1419] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(198), 2,
      sym_simple_path,
      sym__type,
  [1430] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      anon_sym_COMMA,
    ACTIONS(282), 1,
      anon_sym_GT,
    STATE(89), 1,
      aux_sym_generic_argument_list_repeat1,
  [1443] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      sym_identifier,
    ACTIONS(284), 1,
      anon_sym_LBRACE,
    STATE(135), 1,
      sym_compound_path,
  [1456] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_GT,
    ACTIONS(286), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      aux_sym_generic_argument_list_repeat1,
  [1469] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      anon_sym_RBRACE,
    ACTIONS(290), 1,
      anon_sym_COMMA,
    STATE(55), 1,
      aux_sym_compound_path_repeat1,
  [1482] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      sym_identifier,
    ACTIONS(292), 1,
      anon_sym_RBRACE,
    STATE(132), 1,
      sym_compound_path,
  [1495] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      sym_identifier,
    ACTIONS(294), 1,
      anon_sym_RBRACE,
    STATE(132), 1,
      sym_compound_path,
  [1508] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      anon_sym_RBRACE,
    ACTIONS(298), 1,
      anon_sym_COMMA,
    STATE(93), 1,
      aux_sym_compound_path_repeat1,
  [1521] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(146), 2,
      sym_simple_path,
      sym__type,
  [1532] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 1,
      anon_sym_RBRACE,
    ACTIONS(303), 1,
      anon_sym_COMMA,
    STATE(52), 1,
      aux_sym_compound_path_repeat1,
  [1545] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      sym_identifier,
    ACTIONS(305), 1,
      anon_sym_RBRACE,
    STATE(132), 1,
      sym_compound_path,
  [1558] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 1,
      anon_sym_COMMA,
    ACTIONS(310), 1,
      anon_sym_GT,
    STATE(97), 1,
      aux_sym_generic_parameter_list_repeat1,
  [1571] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    ACTIONS(312), 1,
      anon_sym_RBRACE,
    STATE(127), 1,
      sym_simple_path,
  [1584] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(314), 1,
      anon_sym_RBRACE,
    ACTIONS(316), 1,
      anon_sym_COMMA,
    STATE(99), 1,
      aux_sym_export_item_repeat1,
  [1597] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(141), 2,
      sym_simple_path,
      sym__type,
  [1608] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 1,
      anon_sym_RBRACE,
    ACTIONS(319), 1,
      anon_sym_COMMA,
    STATE(93), 1,
      aux_sym_compound_path_repeat1,
  [1621] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 3,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1630] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      anon_sym_RPAREN,
    ACTIONS(323), 1,
      anon_sym_COMMA,
    STATE(76), 1,
      aux_sym_struct_parameter_list_repeat1,
  [1643] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      sym_identifier,
    ACTIONS(325), 1,
      anon_sym_RBRACE,
    STATE(132), 1,
      sym_compound_path,
  [1656] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      sym_identifier,
    ACTIONS(327), 1,
      anon_sym_GT,
    STATE(124), 1,
      sym_generic_parameter,
  [1669] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      sym_identifier,
    ACTIONS(329), 1,
      anon_sym_RBRACE,
    STATE(147), 1,
      sym_union_variant,
  [1682] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      anon_sym_RBRACE,
    ACTIONS(331), 1,
      anon_sym_COMMA,
    STATE(70), 1,
      aux_sym_union_variant_list_repeat1,
  [1695] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      sym_identifier,
    ACTIONS(333), 1,
      anon_sym_GT,
    STATE(62), 1,
      sym_generic_parameter,
  [1708] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      anon_sym_RPAREN,
    ACTIONS(335), 1,
      anon_sym_COMMA,
    STATE(63), 1,
      aux_sym_func_parameter_list_repeat1,
  [1721] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(155), 2,
      sym_simple_path,
      sym__type,
  [1732] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(156), 2,
      sym_simple_path,
      sym__type,
  [1743] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(116), 1,
      sym__pattern,
    ACTIONS(337), 2,
      sym_identifier,
      sym_number,
  [1754] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(175), 2,
      sym_simple_path,
      sym__type,
  [1765] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    ACTIONS(339), 1,
      anon_sym_RBRACE,
    STATE(83), 1,
      sym_simple_path,
  [1778] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1786] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 1,
      anon_sym_COLON,
    ACTIONS(345), 1,
      anon_sym_EQ,
  [1796] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 2,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [1804] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 1,
      anon_sym_SEMI,
    ACTIONS(351), 1,
      anon_sym_RBRACE,
  [1814] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1822] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(355), 1,
      anon_sym_DASH_GT,
    ACTIONS(357), 1,
      anon_sym_LBRACE,
  [1832] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(359), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1840] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(361), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [1848] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_LBRACE,
    STATE(165), 1,
      sym_block,
  [1858] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(310), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [1866] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(363), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1874] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(365), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1882] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(314), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1890] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(367), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1898] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(369), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1906] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      anon_sym_LPAREN,
    STATE(163), 1,
      sym_struct_parameter_list,
  [1916] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(22), 1,
      sym_simple_path,
  [1926] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1934] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(371), 2,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [1942] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(373), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1950] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(375), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1958] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      sym_identifier,
    STATE(147), 1,
      sym_union_variant,
  [1968] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      sym_identifier,
    STATE(132), 1,
      sym_compound_path,
  [1978] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(377), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1986] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      anon_sym_LBRACE,
    STATE(166), 1,
      sym_union_variant_list,
  [1996] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(127), 1,
      sym_simple_path,
  [2006] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(379), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2014] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      anon_sym_LPAREN,
    STATE(71), 1,
      sym_func_parameter_list,
  [2024] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2032] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(381), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [2040] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(122), 1,
      sym_simple_path,
  [2050] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [2058] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [2066] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(23), 1,
      sym_simple_path,
  [2076] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(383), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [2084] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      sym_identifier,
    STATE(124), 1,
      sym_generic_parameter,
  [2094] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(385), 2,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [2102] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2110] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(387), 2,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [2118] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(389), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2126] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(391), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2134] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_LBRACE,
    STATE(185), 1,
      sym_block,
  [2144] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 1,
      anon_sym_SEMI,
    ACTIONS(393), 1,
      anon_sym_RBRACE,
  [2154] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(395), 1,
      anon_sym_SEMI,
  [2161] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(397), 1,
      sym_identifier,
  [2168] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(399), 1,
      anon_sym_SEMI,
  [2175] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(401), 1,
      anon_sym_SEMI,
  [2182] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(403), 1,
      anon_sym_COLON,
  [2189] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(405), 1,
      anon_sym_SEMI,
  [2196] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(407), 1,
      anon_sym_SEMI,
  [2203] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(409), 1,
      anon_sym_SEMI,
  [2210] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(411), 1,
      anon_sym_SEMI,
  [2217] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(413), 1,
      anon_sym_SEMI,
  [2224] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(415), 1,
      anon_sym_SEMI,
  [2231] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(417), 1,
      anon_sym_COLON,
  [2238] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(419), 1,
      anon_sym_SEMI,
  [2245] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(421), 1,
      anon_sym_SEMI,
  [2252] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(423), 1,
      sym_identifier,
  [2259] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(425), 1,
      anon_sym_SEMI,
  [2266] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(427), 1,
      anon_sym_SEMI,
  [2273] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(429), 1,
      anon_sym_LBRACE,
  [2280] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(431), 1,
      anon_sym_SEMI,
  [2287] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(433), 1,
      anon_sym_LBRACE,
  [2294] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(435), 1,
      anon_sym_SEMI,
  [2301] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(437), 1,
      anon_sym_SEMI,
  [2308] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(439), 1,
      anon_sym_SEMI,
  [2315] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(441), 1,
      anon_sym_SEMI,
  [2322] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(443), 1,
      anon_sym_SEMI,
  [2329] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(445), 1,
      anon_sym_SEMI,
  [2336] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(447), 1,
      anon_sym_SEMI,
  [2343] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(449), 1,
      anon_sym_SEMI,
  [2350] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(451), 1,
      anon_sym_SEMI,
  [2357] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(453), 1,
      anon_sym_SEMI,
  [2364] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(455), 1,
      anon_sym_SEMI,
  [2371] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 1,
      anon_sym_SEMI,
  [2378] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(457), 1,
      anon_sym_SEMI,
  [2385] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(459), 1,
      anon_sym_SEMI,
  [2392] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(461), 1,
      anon_sym_SEMI,
  [2399] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(463), 1,
      anon_sym_SEMI,
  [2406] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(465), 1,
      ts_builtin_sym_end,
  [2413] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(467), 1,
      anon_sym_SEMI,
  [2420] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(469), 1,
      sym_identifier,
  [2427] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(471), 1,
      sym_identifier,
  [2434] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(473), 1,
      anon_sym_EQ,
  [2441] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(475), 1,
      anon_sym_SEMI,
  [2448] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(477), 1,
      anon_sym_SEMI,
  [2455] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(479), 1,
      sym_identifier,
  [2462] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(481), 1,
      sym_identifier,
  [2469] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(483), 1,
      anon_sym_SEMI,
  [2476] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(485), 1,
      anon_sym_LBRACE,
  [2483] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(487), 1,
      anon_sym_SEMI,
  [2490] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(489), 1,
      anon_sym_SEMI,
  [2497] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(491), 1,
      anon_sym_LBRACE,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 38,
  [SMALL_STATE(4)] = 75,
  [SMALL_STATE(5)] = 112,
  [SMALL_STATE(6)] = 149,
  [SMALL_STATE(7)] = 186,
  [SMALL_STATE(8)] = 223,
  [SMALL_STATE(9)] = 260,
  [SMALL_STATE(10)] = 297,
  [SMALL_STATE(11)] = 334,
  [SMALL_STATE(12)] = 371,
  [SMALL_STATE(13)] = 393,
  [SMALL_STATE(14)] = 418,
  [SMALL_STATE(15)] = 443,
  [SMALL_STATE(16)] = 458,
  [SMALL_STATE(17)] = 483,
  [SMALL_STATE(18)] = 498,
  [SMALL_STATE(19)] = 513,
  [SMALL_STATE(20)] = 528,
  [SMALL_STATE(21)] = 544,
  [SMALL_STATE(22)] = 558,
  [SMALL_STATE(23)] = 571,
  [SMALL_STATE(24)] = 584,
  [SMALL_STATE(25)] = 604,
  [SMALL_STATE(26)] = 624,
  [SMALL_STATE(27)] = 641,
  [SMALL_STATE(28)] = 660,
  [SMALL_STATE(29)] = 677,
  [SMALL_STATE(30)] = 694,
  [SMALL_STATE(31)] = 713,
  [SMALL_STATE(32)] = 732,
  [SMALL_STATE(33)] = 746,
  [SMALL_STATE(34)] = 760,
  [SMALL_STATE(35)] = 776,
  [SMALL_STATE(36)] = 792,
  [SMALL_STATE(37)] = 806,
  [SMALL_STATE(38)] = 820,
  [SMALL_STATE(39)] = 834,
  [SMALL_STATE(40)] = 850,
  [SMALL_STATE(41)] = 866,
  [SMALL_STATE(42)] = 880,
  [SMALL_STATE(43)] = 892,
  [SMALL_STATE(44)] = 906,
  [SMALL_STATE(45)] = 918,
  [SMALL_STATE(46)] = 930,
  [SMALL_STATE(47)] = 946,
  [SMALL_STATE(48)] = 960,
  [SMALL_STATE(49)] = 974,
  [SMALL_STATE(50)] = 987,
  [SMALL_STATE(51)] = 1000,
  [SMALL_STATE(52)] = 1013,
  [SMALL_STATE(53)] = 1026,
  [SMALL_STATE(54)] = 1039,
  [SMALL_STATE(55)] = 1052,
  [SMALL_STATE(56)] = 1065,
  [SMALL_STATE(57)] = 1074,
  [SMALL_STATE(58)] = 1083,
  [SMALL_STATE(59)] = 1096,
  [SMALL_STATE(60)] = 1105,
  [SMALL_STATE(61)] = 1118,
  [SMALL_STATE(62)] = 1131,
  [SMALL_STATE(63)] = 1144,
  [SMALL_STATE(64)] = 1157,
  [SMALL_STATE(65)] = 1168,
  [SMALL_STATE(66)] = 1181,
  [SMALL_STATE(67)] = 1190,
  [SMALL_STATE(68)] = 1201,
  [SMALL_STATE(69)] = 1214,
  [SMALL_STATE(70)] = 1227,
  [SMALL_STATE(71)] = 1240,
  [SMALL_STATE(72)] = 1253,
  [SMALL_STATE(73)] = 1264,
  [SMALL_STATE(74)] = 1277,
  [SMALL_STATE(75)] = 1290,
  [SMALL_STATE(76)] = 1303,
  [SMALL_STATE(77)] = 1316,
  [SMALL_STATE(78)] = 1325,
  [SMALL_STATE(79)] = 1338,
  [SMALL_STATE(80)] = 1347,
  [SMALL_STATE(81)] = 1360,
  [SMALL_STATE(82)] = 1369,
  [SMALL_STATE(83)] = 1380,
  [SMALL_STATE(84)] = 1393,
  [SMALL_STATE(85)] = 1406,
  [SMALL_STATE(86)] = 1419,
  [SMALL_STATE(87)] = 1430,
  [SMALL_STATE(88)] = 1443,
  [SMALL_STATE(89)] = 1456,
  [SMALL_STATE(90)] = 1469,
  [SMALL_STATE(91)] = 1482,
  [SMALL_STATE(92)] = 1495,
  [SMALL_STATE(93)] = 1508,
  [SMALL_STATE(94)] = 1521,
  [SMALL_STATE(95)] = 1532,
  [SMALL_STATE(96)] = 1545,
  [SMALL_STATE(97)] = 1558,
  [SMALL_STATE(98)] = 1571,
  [SMALL_STATE(99)] = 1584,
  [SMALL_STATE(100)] = 1597,
  [SMALL_STATE(101)] = 1608,
  [SMALL_STATE(102)] = 1621,
  [SMALL_STATE(103)] = 1630,
  [SMALL_STATE(104)] = 1643,
  [SMALL_STATE(105)] = 1656,
  [SMALL_STATE(106)] = 1669,
  [SMALL_STATE(107)] = 1682,
  [SMALL_STATE(108)] = 1695,
  [SMALL_STATE(109)] = 1708,
  [SMALL_STATE(110)] = 1721,
  [SMALL_STATE(111)] = 1732,
  [SMALL_STATE(112)] = 1743,
  [SMALL_STATE(113)] = 1754,
  [SMALL_STATE(114)] = 1765,
  [SMALL_STATE(115)] = 1778,
  [SMALL_STATE(116)] = 1786,
  [SMALL_STATE(117)] = 1796,
  [SMALL_STATE(118)] = 1804,
  [SMALL_STATE(119)] = 1814,
  [SMALL_STATE(120)] = 1822,
  [SMALL_STATE(121)] = 1832,
  [SMALL_STATE(122)] = 1840,
  [SMALL_STATE(123)] = 1848,
  [SMALL_STATE(124)] = 1858,
  [SMALL_STATE(125)] = 1866,
  [SMALL_STATE(126)] = 1874,
  [SMALL_STATE(127)] = 1882,
  [SMALL_STATE(128)] = 1890,
  [SMALL_STATE(129)] = 1898,
  [SMALL_STATE(130)] = 1906,
  [SMALL_STATE(131)] = 1916,
  [SMALL_STATE(132)] = 1926,
  [SMALL_STATE(133)] = 1934,
  [SMALL_STATE(134)] = 1942,
  [SMALL_STATE(135)] = 1950,
  [SMALL_STATE(136)] = 1958,
  [SMALL_STATE(137)] = 1968,
  [SMALL_STATE(138)] = 1978,
  [SMALL_STATE(139)] = 1986,
  [SMALL_STATE(140)] = 1996,
  [SMALL_STATE(141)] = 2006,
  [SMALL_STATE(142)] = 2014,
  [SMALL_STATE(143)] = 2024,
  [SMALL_STATE(144)] = 2032,
  [SMALL_STATE(145)] = 2040,
  [SMALL_STATE(146)] = 2050,
  [SMALL_STATE(147)] = 2058,
  [SMALL_STATE(148)] = 2066,
  [SMALL_STATE(149)] = 2076,
  [SMALL_STATE(150)] = 2084,
  [SMALL_STATE(151)] = 2094,
  [SMALL_STATE(152)] = 2102,
  [SMALL_STATE(153)] = 2110,
  [SMALL_STATE(154)] = 2118,
  [SMALL_STATE(155)] = 2126,
  [SMALL_STATE(156)] = 2134,
  [SMALL_STATE(157)] = 2144,
  [SMALL_STATE(158)] = 2154,
  [SMALL_STATE(159)] = 2161,
  [SMALL_STATE(160)] = 2168,
  [SMALL_STATE(161)] = 2175,
  [SMALL_STATE(162)] = 2182,
  [SMALL_STATE(163)] = 2189,
  [SMALL_STATE(164)] = 2196,
  [SMALL_STATE(165)] = 2203,
  [SMALL_STATE(166)] = 2210,
  [SMALL_STATE(167)] = 2217,
  [SMALL_STATE(168)] = 2224,
  [SMALL_STATE(169)] = 2231,
  [SMALL_STATE(170)] = 2238,
  [SMALL_STATE(171)] = 2245,
  [SMALL_STATE(172)] = 2252,
  [SMALL_STATE(173)] = 2259,
  [SMALL_STATE(174)] = 2266,
  [SMALL_STATE(175)] = 2273,
  [SMALL_STATE(176)] = 2280,
  [SMALL_STATE(177)] = 2287,
  [SMALL_STATE(178)] = 2294,
  [SMALL_STATE(179)] = 2301,
  [SMALL_STATE(180)] = 2308,
  [SMALL_STATE(181)] = 2315,
  [SMALL_STATE(182)] = 2322,
  [SMALL_STATE(183)] = 2329,
  [SMALL_STATE(184)] = 2336,
  [SMALL_STATE(185)] = 2343,
  [SMALL_STATE(186)] = 2350,
  [SMALL_STATE(187)] = 2357,
  [SMALL_STATE(188)] = 2364,
  [SMALL_STATE(189)] = 2371,
  [SMALL_STATE(190)] = 2378,
  [SMALL_STATE(191)] = 2385,
  [SMALL_STATE(192)] = 2392,
  [SMALL_STATE(193)] = 2399,
  [SMALL_STATE(194)] = 2406,
  [SMALL_STATE(195)] = 2413,
  [SMALL_STATE(196)] = 2420,
  [SMALL_STATE(197)] = 2427,
  [SMALL_STATE(198)] = 2434,
  [SMALL_STATE(199)] = 2441,
  [SMALL_STATE(200)] = 2448,
  [SMALL_STATE(201)] = 2455,
  [SMALL_STATE(202)] = 2462,
  [SMALL_STATE(203)] = 2469,
  [SMALL_STATE(204)] = 2476,
  [SMALL_STATE(205)] = 2483,
  [SMALL_STATE(206)] = 2490,
  [SMALL_STATE(207)] = 2497,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(201),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(207),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(204),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(202),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(197),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(196),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(201),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(207),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(204),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(202),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(197),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(196),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(195),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(179),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(164),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(190),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(167),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(173),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(174),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(205),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_simple_path, 1),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(148),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(158),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(157),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(161),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_argument_list, 4),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(112),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(12),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(189),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_argument_list, 5),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_argument_list, 3),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_argument_list, 2),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_simple_path, 2, .production_id = 5),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__item, 2),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_simple_path, 4, .production_id = 5),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_simple_path, 3),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_path, 1),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(172),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(169),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(151),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(153),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__pattern, 1),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(162),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_path, 2, .production_id = 5),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(159),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_variant, 1, .production_id = 4),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 2),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 2),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(206),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 5, .production_id = 23),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_statement, 5, .production_id = 23),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 7, .production_id = 24),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_statement, 7, .production_id = 24),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(199),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(191),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(183),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(184),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_parameter_list, 5),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_parameter_list, 4),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_parameter_list, 2),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(192),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [214] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_func_parameter_list_repeat1, 2), SHIFT_REPEAT(34),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_func_parameter_list_repeat1, 2),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_parameter, 1, .production_id = 4),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(200),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_parameter_list, 2),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_union_variant_list_repeat1, 2),
  [239] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_union_variant_list_repeat1, 2), SHIFT_REPEAT(136),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [244] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_generic_argument_list_repeat1, 2), SHIFT_REPEAT(94),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_generic_argument_list_repeat1, 2),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(180),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [255] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_parameter_list_repeat1, 2), SHIFT_REPEAT(32),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_parameter_list_repeat1, 2),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_parameter_list, 5),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_parameter_list, 3),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_parameter_list, 4),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(168),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(144),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(171),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(182),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_compound_path_repeat1, 2),
  [298] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_path_repeat1, 2), SHIFT_REPEAT(137),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(149),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [307] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_generic_parameter_list_repeat1, 2), SHIFT_REPEAT(150),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_generic_parameter_list_repeat1, 2),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(181),
  [314] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_export_item_repeat1, 2),
  [316] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_export_item_repeat1, 2), SHIFT_REPEAT(140),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_parameter_list, 3),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(176),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(187),
  [341] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_variant, 2, .production_id = 11),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [347] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_parameter_list, 3),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(160),
  [353] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_path, 8, .production_id = 5),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [359] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_path, 7, .production_id = 5),
  [361] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_parameter, 3, .production_id = 14),
  [363] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_path, 7),
  [365] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_path, 6, .production_id = 5),
  [367] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_path, 6),
  [369] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_path, 4),
  [371] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_parameter_list, 5),
  [373] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_parameter, 4, .production_id = 20),
  [375] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_path, 4, .production_id = 5),
  [377] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_path, 3),
  [379] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_parameter, 3, .production_id = 15),
  [381] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_path, 5, .production_id = 5),
  [383] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_path, 5),
  [385] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_parameter_list, 4),
  [387] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_parameter_list, 2),
  [389] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_parameter, 1, .production_id = 6),
  [391] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_parameter, 3, .production_id = 16),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(188),
  [395] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [397] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [399] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, .production_id = 18),
  [401] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [403] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [405] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_item, 4, .production_id = 7),
  [407] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_item, 7, .production_id = 13),
  [409] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_item, 6, .production_id = 17),
  [411] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_item, 4, .production_id = 8),
  [413] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_item, 7, .production_id = 19),
  [415] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_item, 4),
  [417] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [419] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_item, 4, .production_id = 9),
  [421] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_item, 4),
  [423] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [425] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_item, 5, .production_id = 3),
  [427] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_item, 4, .production_id = 3),
  [429] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [431] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_variant_list, 4),
  [433] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [435] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_item, 3, .production_id = 2),
  [437] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_item, 5, .production_id = 10),
  [439] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_variant_list, 5),
  [441] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_item, 6),
  [443] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_item, 6),
  [445] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_variant_list, 2),
  [447] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_item, 5),
  [449] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_item, 7, .production_id = 21),
  [451] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_item, 3, .production_id = 1),
  [453] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_item, 3),
  [455] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, .production_id = 22),
  [457] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_item, 8, .production_id = 19),
  [459] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_item, 5),
  [461] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_item, 3),
  [463] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [465] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [467] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_item, 6, .production_id = 10),
  [469] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [471] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [473] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [475] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [477] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_variant_list, 3),
  [479] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [481] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [483] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_item, 5, .production_id = 12),
  [485] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [487] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_item, 6, .production_id = 13),
  [489] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [491] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_language_test(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const uint16_t *)ts_parse_table,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .field_count = FIELD_COUNT,
    .field_map_slices = (const TSFieldMapSlice *)ts_field_map_slices,
    .field_map_entries = (const TSFieldMapEntry *)ts_field_map_entries,
    .field_names = ts_field_names,
    .large_state_count = LARGE_STATE_COUNT,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .state_count = STATE_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
